### ISSUE TITLE
How to modify /etc/nvidia-container-runtime/config.toml?

### ISSUE THREAD

**Issue by janetat** [NVIDIA/gpu-operator#1027]
How to modify `/etc/nvidia-container-runtime/config.toml`  in `nvidia-contianer-toolkit-daemonset-xxx` installed by helm?
I need `accept-nvidia-visible-devices-envvar-when-unprivileged = true`

**Comment by cdesiniotis** [comment]
You can do this by configuring the following environment variable in ClusterPolicy:
```
toolkit:
  env:
  - name: ACCEPT_NVIDIA_VISIBLE_DEVICES_ENVVAR_WHEN_UNPRIVILEGED
    value: "true"
```
Note that "true" is the default value for this field in the config file.
