### ISSUE TITLE
ServiceAccount `node-feature-discovery` should not be included in ClusterRoleBinding when `nfd.enabled: false`

### ISSUE THREAD

**Issue by cmontemuino** [NVIDIA/gpu-operator#1038]
ServiceAccount `node-feature-discovery` should not be included in ClusterRoleBinding when `nfd.enabled: false`

https://github.com/NVIDIA/gpu-operator/blob/e4f1f5d26c11608379dc234e1e9a316837ce1535/deployments/gpu-operator/templates/clusterrolebinding.yaml#L12-L14

```yaml
- kind: ServiceAccount
  name: node-feature-discovery
  namespace: {{ $.Release.Namespace }}
```
