### ISSUE TITLE
nvidia-dgcm-exporter error

### ISSUE THREAD

**Issue by dummys** [NVIDIA/gpu-operator#107]
After installation, the nvidia-dgcm-exporter pod say this:

```
logs -n gpu-operator-resources nvidia-dcgm-exporter-rjj8f
time="2020-11-24T10:54:00Z" level=info msg="Starting dcgm-exporter"
time="2020-11-24T10:54:00Z" level=info msg="DCGM successfully initialized!"
time="2020-11-24T10:54:00Z" level=fatal msg="Error watching fields: Profiling is not supported for this group of GPUs or GPU"
```
Is there something to configure ? We run 8 nvidia 2080 RTX

**Comment by eachirei** [comment]
I ran into the same issue and fixed it as follows:
1. Use `/etc/dcgm-exporter/default-counters.csv` instead of `dcp-metrics-included.csv`
2. Add `--kubernetes` flag to dcgm exporter daemonset
3. Mount `/var/lib/kubelet/pod-resources` for dcgm exporter daemonset (required for kubernetes pod mapping from step 2)

**Comment by dummys** [comment]
but you are doing this in the POD itself ?
`/etc/dcgm-exporter/default-counters.csv` ?

**Comment by eachirei** [comment]
Check the daemonset definition for dcgm. This is what I changed:
```
spec:
      containers:
      - args:
        - --kubernetes
        - -f
        - /etc/dcgm-exporter/default-counters.csv
        name: nvidia-dcgm-exporter
        volumeMounts:
        - mountPath: /var/lib/kubelet/pod-resources
          name: pod-resources
      volumes:
      - hostPath:
          path: /var/lib/kubelet/pod-resources
          type: ""
        name: pod-resources
```
