### ISSUE TITLE
Question: How to dynamically adjust replicas?

### ISSUE THREAD

**Issue by loprx** [NVIDIA/gpu-operator#1144]
This is my yaml:
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: time-slicing-config-all
data:
  any: |-
    version: v1
    flags:
      migStrategy: none
    sharing:
      timeSlicing:
        renameByDefault: false
        failRequestsGreaterThanOne: false
        resources:
          - name: nvidia.com/gpu
            replicas: 8
```

I tried to modify it directly and `apply` it, but it didn't take effect.

After deleting `configmap`, `reinstall` will still return to its previous value.
