### ISSUE TITLE
i need to install GPU operator with helm and automate this process , so that i can deploy to multiple environments with github actions, can you share the details to achieve this please?

### ISSUE THREAD

**Issue by vamsireddykukati** [NVIDIA/gpu-operator#1161]
i need to install GPU operator with helm and automate this process , so that i can deploy to multiple environments with github actions, can you share the details to achieve this please?

In Azure AKS i have installed GPU nodes. for workloads to be deployed...i need to install GPU operator software ...in to my cluster. kindly provide me reference.

**Comment by chipzoller** [comment]
These values will work for an AKS installation.

```yaml
# These values validated on v24.6.1 of the NVIDIA GPU Operator.
driver:
  enabled: true
toolkit:
  enabled: true
cdi:
  enabled: false
nfd:
  enabled: true
gfd:
  enabled: true
migManager:
  enabled: false
devicePlugin:
  enabled: true
dcgmExporter:
  enabled: true
```
