### ISSUE TITLE
Examples showing how to specify custom MIG config in values.yaml are misformatted

### ISSUE THREAD

**Issue by tomtseng** [NVIDIA/gpu-operator#1259]
Not sure if this is a quirk of my setup or a general bug since I didn't spend time fully debugging this, but I'll document it here anyway in case it's helpful to someone else who has a similar setup.

## Issue 

For my cluster I have a helmfile that contains:
```yaml
# helmfile.yaml
repositories:
- name: nvidia
  url: https://helm.ngc.nvidia.com/nvidia

releases:
- name: gpu-operator
  namespace: gpu-operator
  chart: nvidia/gpu-operator
  version: v24.9.2
  values:
  - gpu-operator.yaml
...
```
where `gpu-operator.yaml` contains
```yaml
# gpu-operator.yaml
...
mig:
 strategy: mixed
migManager:
  enabled: true
  config:
    name: custom-mig-config
    default: all-disabled
    create: true
    data: |-
      config.yaml: |-
        version: v1
        mig-configs:
          all-disabled:
            - devices: all
              mig-enabled: false

          2g-2g-2g-1g-and-4g-3g:
            - devices: [0]
              mig-enabled: true
              mig-devices:
                "2g.20gb": 3
                "1g.10gb": 1
            - devices: [1]
              mig-enabled: true
              mig-devices:
                "4g.40gb": 1
                "3g.40gb": 1
            - devices: [2,3,4,5,6,7]
              mig-enabled: false
```

Then I install `gpu-operator` with `helmfile apply helmfile.yaml --interactive`. However I get this error:
```
  coalesce.go:286: warning: cannot overwrite table with non table for gpu-operator.migManager.config.data (map[])
  coalesce.go:286: warning: cannot overwrite table with non table for gpu-operator.migManager.config.data (map[])
  Error: UPGRADE FAILED: failed to create resource: ConfigMap in version "v1" cannot be handled as a ConfigMap: json: cannot unmarshal string into Go struct field ConfigMap.data of type map[string]string
```

## Fix

Remove the `|-` after `data:`. However I had thought the `|-` to be necessary because it's shown in both [the docs](https://docs.nvidia.com/datacenter/cloud-native/gpu-operator/24.9.1/gpu-operator-mig.html#example-custom-mig-configuration-during-installation) and the [comments in the source gpu-operator/values.yaml](https://github.com/NVIDIA/gpu-operator/blob/v24.9.2/deployments/gpu-operator/values.yaml#L387).

## Versions

`gpu-operator` v24.9.2
`helmfile` v0.169.2
macOS Sequoia 15.3
