### ISSUE TITLE
nvidia-operator-validator cannot check host driver installation state but cuda-sample:vectoradd-cuda runs successfully

### ISSUE THREAD

**Issue by davidshen84** [NVIDIA/gpu-operator#1276]
- OS: Gentoo Linux
- k8s: k3s v1.31.5+k3s1
- nvidia driver version: 550.144.03
- libnvidia-container version: 1.17.2
- nvidia-container-toolkit version: 1.17.3

```
  helm upgrade --install --wait gpu-operator-1739580441 \
       --namespace gpu-operator --create-namespace \
       nvidia/gpu-operator \
       --version=v24.9.2 \
       --set driver.enabled=false,toolkit.enabled=false
```

In the `nvidia-operator-validator` pod, the `driver-validation` container keeps logging the following message while the other containers are stuck in the initializing state.

```
Attempting to validate a driver container installation
failed to validate the driver, retrying after 5 seconds\n
```

However, if I run a pod like the following, note I removed the resource request and added `runtimeClassName`.

```yaml
  apiVersion: v1
  kind: Pod
  metadata:
    name: cuda-vectoradd
  spec:
    restartPolicy: OnFailure
    runtimeClassName: nvidia
    containers:
      - name: cuda-vectoradd
        image: nvcr.io/nvidia/k8s/cuda-sample:vectoradd-cuda11.7.1-ubuntu20.04
```

The pod ran successfully with these messages in the log.

```
[Vector addition of 50000 elements]
Copy input data from the host memory to the CUDA device
CUDA kernel launch with 196 blocks of 256 threads
Copy output data from the CUDA device to the host memory
Test PASSED
Done
```

Note, I have set `driver.enabled=false` for the gpu-operator chart, but the message still says, "Attempting to validate a driver container installation". Maybe the validator should validate the driver in my host OS?

Thanks

**Comment by davidshen84** [comment]
I did a system reboot and waited for a long time; somehow, all pods are running now.

But if I launch a pod with `nvidia.com/gpu: 1` resource limits, the pod won't start due to insufficient resources.

I checked the node status. I have the `nvidia.com/gpu.present: "true"` label. However, I could not find any information about the number of GPUs I have on that node.

**Comment by davidshen84** [comment]
Oh...Gentoo

On Gentoo, they put vendor-provided binaries to `/opt/bin`, so the `nvidia-smi` is at `/opt/bin/nvidia-smi`, while the validator expects to locate it at `/host/usr/bin/nvidia-smi`, which maps to `/usr/bin/nvidia-smi` on my host.

**Comment by planetbeing** [comment]
I'm running into the same issue on Talos, who had put it in `/host/usr/local/bin/nvidia-smi`. The attempted `chroot /host nvidia-smi` works because it's in the path.

I wouldn't blame Gentoo or Talos. Paths should never be hardcoded.

**Comment by hzhangxyz** [comment]
> I'm running into the same issue on Talos, who had put it in `/host/usr/local/bin/nvidia-smi`. The attempted `chroot /host nvidia-smi` works because it's in the path.
> 
> I wouldn't blame Gentoo or Talos. Paths should never be hardcoded.

Hello, I meet the same situation, how did you resolve this on Talos?

**Comment by hzhangxyz** [comment]
I noticed there a closed PR in https://github.com/NVIDIA/gpu-operator/pull/1050 , it seems something broken again?

**Comment by hzhangxyz** [comment]
It seems the key point of this issue is located at
https://github.com/NVIDIA/gpu-operator/blob/0dd238e31dcfb97afb628cc144e3bba609503798/cmd/nvidia-validator/main.go#L769-L781

It checks in two step, success of either of two leads to success of the whole check.
- https://github.com/NVIDIA/gpu-operator/blob/0dd238e31dcfb97afb628cc144e3bba609503798/cmd/nvidia-validator/main.go#L699-L717
- https://github.com/NVIDIA/gpu-operator/blob/0dd238e31dcfb97afb628cc144e3bba609503798/cmd/nvidia-validator/main.go#L732-L752

**Comment by hzhangxyz** [comment]
According to the git blame, version before https://github.com/NVIDIA/gpu-operator/commit/7d3a8a28c723ac5552a9d10a43dd58f8fb2d47c8 this commit will success since it only check chroot /host nvidia-smi . but that commit add a check by the absolute path, which failed, so the first check failed since that commit.

**Comment by hzhangxyz** [comment]
The second check always fails since it stuck into finding libnvidia-ml.so.1 in several hard coded library path as

https://github.com/NVIDIA/gpu-operator/blob/0dd238e31dcfb97afb628cc144e3bba609503798/cmd/nvidia-validator/find.go#L29-L45

**Comment by hzhangxyz** [comment]
OK, so why we use it well until this week?

**Comment by hzhangxyz** [comment]
Is it because fix in Talos side in https://github.com/siderolabs/extensions/pull/473 ?

**Comment by planetbeing** [comment]
> > I'm running into the same issue on Talos, who had put it in `/host/usr/local/bin/nvidia-smi`. The attempted `chroot /host nvidia-smi` works because it's in the path.
> > I wouldn't blame Gentoo or Talos. Paths should never be hardcoded.
> 
> Hello, I meet the same situation, how did you resolve this on Talos?

I was unable to work around this so I was unable to get gpu-operator to work. Instead, I gave up and just used this: https://www.talos.dev/v1.11/talos-guides/configuration/nvidia-gpu-proprietary/. This is not relevant to this issue, but I'll just put it here to spare you the grief I experienced trying to get this to work. One issue my linked document didn't cover is that Node Feature Discovery must also be working, and labelling the nodes with the GPUs, or else nothing will ever get scheduled. Here is my Argo CD app for that part. You can discern that I had to set some custom arguments in order for the node to be labelled properly to satisfy NVIDIA device plugin's requirements (or I believe you can also label the node manually).

```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: node-feature-discovery
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io/node-feature-discovery
spec:
  project: charts
  destination:
    server: https://kubernetes.default.svc
    namespace: node-feature-discovery
  sources:
    - repoURL: https://github.com/planetbeing/home.git
      path: infrastructure/node-feature-discovery
      targetRevision: HEAD
    - repoURL: https://kubernetes-sigs.github.io/node-feature-discovery/charts
      chart: node-feature-discovery
      targetRevision: 0.17.3
      helm:
        values: |
          worker:
            config:
              sources:
                pci:
                  deviceLabelFields:
                    - vendor

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
  revisionHistoryLimit: 10
```
