### ISSUE TITLE
Adding profile to 'mig.config' does not apply MIG configuration

### ISSUE THREAD

**Issue by simgyuryeol** [NVIDIA/gpu-operator#1286]
### What happened:
I set `all-7g.80gb` or `all-balanced` as the profile in the `mig.config` of my GPU node, but the MIG configuration is not being applied.

![Image](https://github.com/user-attachments/assets/04523ad5-78e3-4195-95ee-971e8f18ceab)

I am currently using one H100 80GB and gpu-operator version 23.4 on my GPU node. 
And I want to use time slicing on other GPU nodes and apply MIG only on my current H100 node.

My `values.yaml` for gpu-operator 23.4 is as follows:
```
mig:
  strategy: "mixed"

devicePlugin:
  enabled: true
  repository: nvcr.io/nvidia
  image: k8s-device-plugin
  version: v0.15.0-ubi8
  imagePullPolicy: IfNotPresent
  imagePullSecrets: []
  args: []
  env:
    - name: PASS_DEVICE_SPECS
      value: "true"
    - name: FAIL_ON_INIT_ERROR
      value: "true"
    - name: DEVICE_LIST_STRATEGY
      value: envvar
    - name: DEVICE_ID_STRATEGY
      value: uuid
    - name: NVIDIA_VISIBLE_DEVICES
      value: all
    - name: NVIDIA_DRIVER_CAPABILITIES
      value: all
  resources: {}
  # Plugin configuration
  # Use "name" to either point to an existing ConfigMap or to create a new one with a list of configurations(i.e with create=true).
  # Use "data" to build an integrated ConfigMap from a set of configurations as
  # part of this helm chart. An example of setting "data" might be:
  # config:
  #   name: device-plugin-config
  #   create: true
  #   data:
  #     default: |-
  #       version: v1
  #       flags:
  #         migStrategy: none
  #     mig-single: |-
  #       version: v1
  #       flags:
  #         migStrategy: single
  #     mig-mixed: |-
  #       version: v1
  #       flags:
  #         migStrategy: mixed
  config:
    # Create a ConfigMap (default: false)
    create: true
    # ConfigMap name (either exiting or to create a new one with create=true above)
    name: "time-slicing-config"
    # Default config name within the ConfigMap
    default: ""
    # Data section for the ConfigMap to create (i.e only applies when create=true)
    data:
      any: |-
        version: v1
        flags:
          migStrategy: mixed
        sharing:
          timeSlicing:
            resources:
            - name: nvidia.com/gpu
              replicas: 8
  # MPS related configuration for the plugin
  mps:
    # MPS root path on the host
    root: "/run/nvidia/mps"

migManager:
  enabled: true
  repository: nvcr.io/nvidia/cloud-native
  image: k8s-mig-manager
  version: v0.7.0-ubuntu20.04
  imagePullPolicy: IfNotPresent
  imagePullSecrets: []
  env:
    - name: WITH_REBOOT
      value: "false"
  resources: {}
  config:
    name: "default-mig-parted-config"
    default: "all-disabled"
  gpuClientsConfig:
    name: "default-mig-parted-config"

```

### question : 
1. I would like to know what is causing this problem and how to fix it.

2. If you look at the log record of `nvidia-mig-manger`, it is as shown in the figure below. 
`/gpu-clients` only contains `config.yaml`, but there is no `clients.yaml`. Is it because the settings are wrong when it is added automatically? Or do I need to add the file explicitly?
![Image](https://github.com/user-attachments/assets/8f5a89f4-cb50-490f-b2c3-a175e0791f8f)

3. I want to configure my 80GB GPU into 40GB, 20GB, and 20GB partitions, but what I want is not in the profile, so I am curious about other options.

4. When I access the node server and run `sudo nvidia-smi mig -cgi 5,14,15 -C`, the MIG instance runs normally. What is the difference between this method and the method of setting `mig.config`? Which method is preferred and why?

5. Is there a good way to set up time slicing and MIG on a per-node basis?
