### ISSUE TITLE
Kubernetes H100 more than 7 Containers

### ISSUE THREAD

**Issue by lgruendh** [NVIDIA/gpu-operator#1287]
We are currently using a H100 within Kubernetes, a second one is on the way.
Our developers have more than 7 containers which need GPU resources.
Currently they should work with K8s Jobs to not reserve the whole GPU with just a few apps.
Is there a better way to run more containers on a single H100?

Also, there is one app which needs more than 10GB of GPU Memory, can we dynamically set MIG devices?

GPU Operator Helm Chart:

```
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: gpu-operator
  namespace: helminstalls
spec:
  chart: gpu-operator
  repo: https://helm.ngc.nvidia.com/nvidia
  targetNamespace: gpu-operator
  version: v24.9.1
  valuesContent: |-
    mig:
      strategy: mixed
    migManager:
      config:
        name: custom-mig-parted-configs-egger
        create: true
        data:
          config.yaml: |-
            version: v1
            mig-configs:
              custom-mig:
                - devices: [0]
                  mig-enabled: true
                  mig-devices:
                    "1g.10gb": 4
                    "3g.40gb": 1
```
