### ISSUE TITLE
ClusterPolicy custom resource is created, eventhough chart is configured to use NVIDIADriver custom resource

### ISSUE THREAD

**Issue by Johannesm299** [NVIDIA/gpu-operator#1299]
When installing the current version of the gpu-operator with the following values:

```
driver:
  enabled: true
  nvidiaDriverCRD:
    enabled: true
    deployDefaultCR: false
```

the `ClusterPolicy` custom resource is still being created. When applying a NVIDIADriver resource afterwards:

```
apiVersion: nvidia.com/v1alpha1
kind: NVIDIADriver
metadata:
  name: driver-gpu-node-group-a
spec:
  driverType: gpu
  image: driver
  imagePullPolicy: IfNotPresent
  nodeSelector:
    node-group/gpu: a
  repository: nvcr.io/nvidia
  tolerations:
    - key: purpose
      operator: Equal
      value: gpu
      effect: NoSchedule
  version: 550.90.07
```

it installs the correct drivers and the driver DaemonSet seems to be managed by the NVIDIADriver resource. So in general everything is working.

I'm wondering then why is the ClusterPolicy resource still being created? The way I read [the documentation of the NVIDIADriver CRD](https://docs.nvidia.com/datacenter/cloud-native/gpu-operator/latest/gpu-driver-configuration.html#comparison-managing-the-driver-with-crd-versus-the-cluster-policy), it seems to be an either or and not both. 

So, is it the correct behavior by the helm chart to install the ClusterPolicy resource, even though it should not be used to manage the gpu driver?
