### ISSUE TITLE
Unable to remove the default taints

### ISSUE THREAD

**Issue by dmildh-absci** [NVIDIA/gpu-operator#1316]
Hello everyone.  I cannot seem to disable to the default NoSchedule taint being applied on first boot up.  I am installing via helm using chart version v24.9.2.

```
  taints:
  - effect: NoSchedule
    key: nvidia.com/gpu
    value: present
```

I have tried using the following values but luck
`
node-feature-discovery.master.config.enableTaints: false`

`node-feature-discovery.master.enableTaints: false`

This is the complete helm values as well

```
driver:
  enabled: false
  rdma:
    enabled: true
    useHostMofed: true
mig:
  strategy: mixed
operator:
  cleanupCRD: false
  defaultRuntime: containerd
  resources:
    limits:
      memory: 1Gi
    requests:
      memory: 512Mi
psa:
  enabled: false
toolkit:
  enabled: true
node-feature-discovery:
  master:
    config:
      enableTaints: false
```
