### ISSUE TITLE
MicroK8s containerd-template.toml is wrong when docker is installed in paralllel

### ISSUE THREAD

**Issue by s-bernhardt** [NVIDIA/gpu-operator#1367]
Hi, I have the following situation where the toolkit breaks the MicroK8s containerd config file.

Ubuntu 22.04 LTS
Nvidia Driver version: 550
MicroK8s version: 1.31
docker version: 24.0.4 
gpu-operator helm chart version: v24.9.2

helm values:
```yaml
driver:
  enabled: "false"
operator:
  defaultRuntime: containerd
toolkit:
  enabled: "true"
  env:
  - name: CONTAINERD_CONFIG
    value: /var/snap/microk8s/current/args/containerd-template.toml
  - name: CONTAINERD_SOCKET
    value: /var/snap/microk8s/common/run/containerd.sock
  - name: CONTAINERD_SET_AS_DEFAULT
    value: "1"
```

The config file is valid and the service starts fine when I remove the following lines:

```bash
disabled_plugins = ["cri"]
imports = ["/etc/containerd/config.toml"]
plugin_dir = ""
required_plugins = []
root = "/var/lib/containerd"
state = "/run/containerd"
temp = ""
```

so the file just starts as usual with:
```bash
oom_score = 0
version = 2
```

the toolkit works fine, when docker is uninstalled during the pod start. as soon as docker is available with its own containerd, the toolkit is somehow detecting it and writing a bad config.

any hint how I can prevent that? I need docker at the same host, because it is my dev environment.

regards
Stefan
