### ISSUE TITLE
GPU related labels persists on the nodes even after uninstalling GPU Operator

### ISSUE THREAD

**Issue by rajendragosavi** [NVIDIA/gpu-operator#1391]
_**Important Note:  NVIDIA AI Enterprise customers can get support from NVIDIA Enterprise support. Please open a case [here](https://enterprise-support.nvidia.com/s/create-case)**._

**Describe the bug**

The Nvidia GPU related labels persists on the nodes, even after completely uninstalling Nvidia GPU operator from the cluster. I used the steps from [here](https://docs.nvidia.com/datacenter/cloud-native/gpu-operator/25.3.0/uninstall.html)

**To Reproduce**

1. Install Nvidia GPU Operator on the Kuberenetes cluster where are there at least one GPU attached to the node.
2. Check the labels on the node. There will be many labels related to GPU configurations.
3. Now uninstall the Nvidia GPU operator using steps from [here](https://docs.nvidia.com/datacenter/cloud-native/gpu-operator/25.3.0/uninstall.html)
4. Check the node labels again, you will see there are still many GPU related labels are present on the node.

**Expected behavior**

Ideally, after the Nvidia GPU operator has uninstalled from the cluster, there should not be any labels present on the nodes related to GPU configurations. 

**Environment (please provide the following information):**
 - GPU Operator Version: [e.g. v25.3.0]
 - OS: [e.g. Ubuntu 20.04.6]
 - Kernel Version: [5.4.0-205-generic]
 - Container Runtime Version: [containerd://1.7.24]
 - Kubernetes Distro and Version: [v1.31.1]

**Information to [attach](https://help.github.com/articles/file-attachments-on-issues-and-pull-requests/)** (optional if deemed irrelevant)

These are the labels present on the node after I have installed the Nvidia GPU operator from the cluster

```
labels:
    beta.kubernetes.io/arch: amd64
    beta.kubernetes.io/instance-type: ao.3.48.128_H100
    beta.kubernetes.io/os: linux
    failure-domain.beta.kubernetes.io/region: SJC3
    failure-domain.beta.kubernetes.io/zone: az1
    kubernetes.io/arch: amd64
    kubernetes.io/hostname: pooler-1744029339851
    kubernetes.io/os: linux
    node-role.kubernetes.io/worker: ""
    node.kubernetes.io/instance-type: ao.3.48.128_H100
    nodepool.ngpc.rxt.io/name: 2d7efc16-67ef-47ee-839a-f6bf04531195
    nvidia.com/gpu-driver-upgrade-state: upgrade-done
    nvidia.com/gpu.deploy.container-toolkit: "true"
    nvidia.com/gpu.deploy.dcgm: "true"
    nvidia.com/gpu.deploy.dcgm-exporter: "true"
    nvidia.com/gpu.deploy.device-plugin: "true"
    nvidia.com/gpu.deploy.driver: "true"
    nvidia.com/gpu.deploy.gpu-feature-discovery: "true"
    nvidia.com/gpu.deploy.node-status-exporter: "true"
    nvidia.com/gpu.deploy.nvsm: ""
    nvidia.com/gpu.deploy.operator-validator: "true"
    nvidia.com/gpu.present: "true"
```
