### ISSUE TITLE
How to avoid running nvidia-device-plugin-validation

### ISSUE THREAD

**Issue by dignajar** [NVIDIA/gpu-operator#140]
I'm installing gpu-operator via Helm and everything works fine, but I have enabled Cluster Autoscaler (CA) and my autoscaling group for GPUs instances has a min of 0 instances, so if I don't have any pod running with GPU the CA scale down the nodes with GPU to 0 instances.My instances have only 1 GPU.

This is the issue I have:
0- There are no pods running that need GPU, and no GPU instances available.
1- I deploy a pod with the need for GPU resources.
2- CA scale up the instance group with GPU.
3- GPU Operator deploy the pods needed to install the drivers in the new node.
4- My pod with my application is deployed in the new node and starts working, using the only GPU available on the node.
5- GPU Operator deploys the pod nvidia-device-plugin-validation that also needs a GPU to run, the node does not have a second GPU so Cluster Autoscaler triggers a new node for the deployment of nvidia-device-plugin-validation.

I would like to know if it is possible to disable the deployment of the pod nvidia-device-plugin-validation or somehow assure that the nvidia-device-plugin-validation pod is deployed first, which would then allow other pod needing GPU to run on the node, after the validation is finished.

Thanks!

**Comment by klueska** [comment]
Thanks for reporting this. We are currently looking into ways to avoid this. We should have an update by the 1.6.0 release in a month or so. Will report back here once we have a concrete plan for mitigating this.

**Comment by dignajar** [comment]
Thanks @klueska

**Comment by mangokingTW** [comment]
@klueska Did the 1.6.0 release fix the issue? I cannot find an option to avoid running nvidia-device-plugin-validation in the helm chart.

**Comment by trevorbox** [comment]
This validation pod also seems to affect the ability of the CA to scale down a node group to 0 and remains in pending state. Any update on this?

**Comment by dignajar** [comment]
I checked the changelog and looks like is not implemented yet.

@klueska can you give us some feedback ? thanks

**Comment by klueska** [comment]
I chatted with @shivamerla a bit about this a while back and I know he has some WIP code to address this. Will let him update with the actual status.

**Comment by shivamerla** [comment]
@dignajar We are trying to address this with 1.7.0 release targeted for end of this month.

**Comment by shivamerla** [comment]
@dignajar `v1.7.0` of GPU operator is now released. You can avoid running plugin validation pod by passing options `--set validator.plugin.env[0].name=WITH_WORKLOAD --set-string validator.plugin.env[0].value=false`. Please re-open this if you still face any issues.

**Comment by dignajar** [comment]
Super! I will test it.
Thank you guys!

**Comment by GuoLiuFang** [comment]
> Super! I will test it.
> Thank you guys!

Does it work?

**Comment by dignajar** [comment]
> > Super! I will test it.
> > Thank you guys!
> 
> Does it work?

I tested in my SBX environment and I have some issue with a missing Docker image `nvidia/driver:460.73.01-centos7`. I didn't have the time to follow the installation, but looks like is missing that image for Centos7.

**Comment by dignajar** [comment]
Works perfect! but I had to set the old drivers for my Centos.

I have differents node selectors and taints, this are my values:

```
    nfd:
      enabled: true

    validator:
      nodeSelector:
        instance-type: gpu
      tolerations:
      - key: "dedicated"
        operator: "Equal"
        value: "gpu"
        effect: "NoSchedule"
      plugin:
        env:
          - name: WITH_WORKLOAD
            value: "false"

    operator:
      tolerations:
      - key: "node-role.kubernetes.io/master"
        operator: "Exists"
        effect: "NoSchedule"

    driver:
      version: "460.32.03"
      nodeSelector:
        instance-type: gpu
      tolerations:
      - key: "dedicated"
        operator: "Equal"
        value: "gpu"
        effect: "NoSchedule"
      repoConfig:
        configMapName: repo-config
        destinationDir: /etc/yum.repos.d

    toolkit:
      version: 1.4.0-ubi8
      nodeSelector:
        instance-type: gpu
      tolerations:
      - key: "dedicated"
        operator: "Equal"
        value: "gpu"
        effect: "NoSchedule"

    devicePlugin:
      nodeSelector:
        instance-type: gpu
      tolerations:
      - key: "dedicated"
        operator: "Equal"
        value: "gpu"
        effect: "NoSchedule"

    dcgmExporter:
      nodeSelector:
        instance-type: gpu
      tolerations:
      - key: "dedicated"
        operator: "Equal"
        value: "gpu"
        effect: "NoSchedule"

    gfd:
      nodeSelector:
        instance-type: gpu
      tolerations:
      - key: "dedicated"
        operator: "Equal"
        value: "gpu"
        effect: "NoSchedule"

    migManager:
      nodeSelector:
        instance-type: gpu
      tolerations:
      - key: "dedicated"
        operator: "Equal"
        value: "gpu"
        effect: "NoSchedule"

    node-feature-discovery:
      worker:
        nodeSelector:
          instance-type: gpu
        tolerations:
        - key: "dedicated"
          operator: "Equal"
          value: "gpu"
          effect: "NoSchedule"
```
