### ISSUE TITLE
k8s-driver-manager v0.8.0 needs Role update

### ISSUE THREAD

**Issue by xhejtman** [NVIDIA/gpu-operator#1499]
_**Important Note:  NVIDIA AI Enterprise customers can get support from NVIDIA Enterprise support. Please open a case [here](https://enterprise-support.nvidia.com/s/create-case)**._

**Describe the bug**

It seems that k8s-driver-manager v0.8.0 needs Role update, as it complains:
```
E0623 22:06:11.893804  393069 reflector.go:166] "Unhandled Error" err="k8s.io/client-go/tools/watch/informerwatcher.go:146: Failed to watch *unstructured.Unstructured: pods \"nvidia-container-toolkit-daemonset-tzjbz\" is forbidden: User \"system:serviceaccount:gpu-operator:nvidia-gpu-driver-driver-570.148.08-ubuntu24.04\" cannot watch resource \"pods\" in API group \"\" in the namespace \"gpu-operator\""
```

Indeed, the nvidia-built-in Role for the service account contains only:
```
rules:
  - apiGroups:
      - security.openshift.io
    resourceNames:
      - privileged
    resources:
      - securitycontextconstraints
    verbs:
      - use
```

**To Reproduce**
Detailed steps to reproduce the issue.

use k8s-driver-manager v0.8.0 and watch the log.

**Expected behavior**

Fixed role, so that the driver-manager does not complain.

**Environment (please provide the following information):**
 - GPU Operator Version: v25.3.1
 - OS: Ubuntu 24.04
 - Kernel Version: 6.11.0-26-generic
 - Container Runtime Version: containerd 2.0.0
 - Kubernetes Distro and Version: RKE2
