### ISSUE TITLE
GPU Operator Image Relocation is hard with automated tooling like kbld

### ISSUE THREAD

**Issue by voor** [NVIDIA/gpu-operator#153]
Looking at an example of the CRD for the NVIDIA Operator:

```
apiVersion: nvidia.com/v1
kind: ClusterPolicy
metadata:
  name: cluster-policy
  namespace: gpu-operator-resources
  labels:
    app.kubernetes.io/component: gpu-operator
spec:
  operator:
    defaultRuntime: containerd
    validator:
      repository: nvcr.io/nvidia/k8s
      image: cuda-sample
      version: vectoradd-cuda10.2
      imagePullPolicy: IfNotPresent
  driver:
    repository: nvcr.io/nvidia
    image: driver
    version: 450.80.02
    imagePullPolicy: IfNotPresent
    tolerations:
    - effect: NoSchedule
      key: nvidia.com/gpu
      operator: Exists
    nodeSelector:
      nvidia.com/gpu.present: "true"
    securityContext:
      privileged: true
      seLinuxOptions:
        level: s0
  toolkit:
    repository: nvcr.io/nvidia/k8s
    image: container-toolkit
    version: 1.4.4-ubuntu18.04
    imagePullPolicy: IfNotPresent
    tolerations:
    - key: CriticalAddonsOnly
      operator: Exists
    - effect: NoSchedule
      key: nvidia.com/gpu
      operator: Exists
    nodeSelector:
      nvidia.com/gpu.present: "true"
    securityContext:
      privileged: true
      seLinuxOptions:
        level: s0
  devicePlugin:
    repository: nvcr.io/nvidia
    image: k8s-device-plugin
    version: v0.8.1
    imagePullPolicy: IfNotPresent
    nodeSelector:
      nvidia.com/gpu.present: "true"
    securityContext:
      privileged: true
    args:
    - --mig-strategy=single
    - --pass-device-specs=false
    - --fail-on-init-error=true
    - --device-list-strategy=envvar
    - --nvidia-driver-root=/run/nvidia/driver
  dcgmExporter:
    repository: nvcr.io/nvidia/k8s
    image: dcgm-exporter
    version: 2.0.13-2.1.2-ubuntu20.04
    imagePullPolicy: IfNotPresent
    args:
    - -f
    - /etc/dcgm-exporter/dcp-metrics-included.csv
  gfd:
    repository: nvcr.io/nvidia
    image: gpu-feature-discovery
    version: v0.4.0
    imagePullPolicy: IfNotPresent
    nodeSelector:
      nvidia.com/gpu.present: "true"
    migStrategy: single
    discoveryIntervalSeconds: 60
```

Now specifically looking at:
```
    repository: nvcr.io/nvidia
    image: gpu-feature-discovery
    version: v0.4.0
```

While this definitely follows a common pattern seen in most Helm charts, at a pure Kubernetes level this format of separating repository, image, and version makes it very hard to inject a sha256 hashed image.  When trying to use resolution and relocation tooling like [kbld](https://carvel.dev/kbld/) you'll actually get errors as using `image` is triggering its auto-discovery in unintended ways:

```
kbld: Error: 
- Resolving image 'driver': GET https://index.docker.io/v2/library/driver/manifests/latest: UNAUTHORIZED: authentication required; [map[Action:pull Class: Name:library/driver Type:repository]]
- Resolving image 'cuda-sample': GET https://index.docker.io/v2/library/cuda-sample/manifests/latest: UNAUTHORIZED: authentication required; [map[Action:pull Class: Name:library/cuda-sample Type:repository]]
- Resolving image 'container-toolkit': GET https://index.docker.io/v2/library/container-toolkit/manifests/latest: UNAUTHORIZED: authentication required; [map[Action:pull Class: Name:library/container-toolkit Type:repository]]
- Resolving image 'dcgm-exporter': GET https://index.docker.io/v2/library/dcgm-exporter/manifests/latest: UNAUTHORIZED: authentication required; [map[Action:pull Class: Name:library/dcgm-exporter Type:repository]]
- Resolving image 'gpu-feature-discovery': GET https://index.docker.io/v2/library/gpu-feature-discovery/manifests/latest: UNAUTHORIZED: authentication required; [map[Action:pull Class: Name:library/gpu-feature-discovery Type:repository]]
- Resolving image 'k8s-device-plugin': GET https://index.docker.io/v2/library/k8s-device-plugin/manifests/latest: UNAUTHORIZED: authentication required; [map[Action:pull Class: Name:library/k8s-device-plugin Type:repository]]
```

Is there an optional way to provide the full image name rather than dissecting it into 3 parts?

So instead of:
```
  devicePlugin:
    repository: nvcr.io/nvidia
    image: k8s-device-plugin
    version: v0.8.1
```
You could have:
```
  devicePlugin:
    fullImage: nvcr.io/nvidia/k8s-device-plugin:v0.8.1
```
which could then be properly handled for resolution and relocation?

Also, how do you override the `nvcr.io/nvidia/cuda@sha256:ed723a1339cddd75eb9f2be2f3476edf497a1b189c10c9bf9eb8da4a16a51a59` reference in the init containers?
