### ISSUE TITLE
Error: ClusterPolicy.nvidia.com "cluster-policy" is invalid

### ISSUE THREAD

**Issue by joedborg** [NVIDIA/gpu-operator#174]
### 1. Quick Debug Checklist
- [x] Are you running on an Ubuntu 18.04 node?
- [x] Are you running Kubernetes v1.13+?
- [ ] Are you running Docker (>= 18.06) or CRIO (>= 1.13+)? 
* No, running containerd 1.4.3
- [x] Do you have `i2c_core` and `ipmi_msghandler` loaded on the nodes?
- [ ] Did you apply the CRD (`kubectl describe clusterpolicies --all-namespaces`)
* Applied via helm3 (https://docs.nvidia.com/datacenter/cloud-native/gpu-operator/getting-started.html)

### 1. Issue or feature description

This is on K8s 1.20.5.  It seems to be a new problem as this used to work fine.

```
Error: ClusterPolicy.nvidia.com "cluster-policy" is invalid: [spec.driver.licensingConfig.configMapName: Invalid value: "null": spec.driver.licensingConfig.configMapName in body must be of type string: "null", spec.driver.repoConfig.destinationDir: Invalid value: "null": spec.driver.repoConfig.destinationDir in body must be of type string: "null", spec.driver.repoConfig.configMapName: Invalid value: "null": spec.driver.repoConfig.configMapName in body must be of type string: "null"]
```
Pods come up fine, but node is not tagged with `nvidia.com/gpu`, so nothing, that requires GPU, will schedule.

### 2. Steps to reproduce the issue

Follow https://docs.nvidia.com/datacenter/cloud-native/gpu-operator/getting-started.html#install-the-gpu-operator

**Comment by joedborg** [comment]
This seems to be working fine with 1.21 beta 1.  Has something been updated in the helm chart that's not backwards compatible?

**Comment by shivamerla** [comment]
@joedborg Can you delete the clusterpolicies CRD and re-install to confirm?

**Comment by joedborg** [comment]
@shivamerla yep, I've tried from a clean cluster too.

**Comment by shivamerla** [comment]
@joedborg Which Helm chart version are you trying to install? Can you copy the install command and values.yaml if overwritten please?

**Comment by joedborg** [comment]
@shivamerla 
```
helm install gpu-operator nvidia/gpu-operator \
  --set operator.defaultRuntime=containerd \
  --set toolkit.version=1.4.4-ubuntu18.04
```

**Comment by shivamerla** [comment]
@joedborg Default values.yaml file has these defined as empty string values. So wondering what else is causing this. Can you check outoput of "helm show values nvidia/gpu-operator --version=1.6.2" and confirm these are set correctly?

```
  # private mirror repository configuration
  repoConfig:
    configMapName: ""
    destinationDir: ""
  # vGPU licensing configuration
  licensingConfig:
    configMapName: ""
```

**Comment by gecube** [comment]
I was hit by the same issue. I used the instructions from https://developer.nvidia.com/blog/announcing-containerd-support-for-the-nvidia-gpu-operator/

```
helm install --wait --generate-name \
    nvidia/gpu-operator \
    --set operator.defaultRuntime=containerd \
    --set toolkit.env[0].name=CONTAINERD_CONFIG \
    --set toolkit.env[0].value=/etc/containerd/config.toml \
    --set toolkit.env[1].name=CONTAINERD_SOCKET \
    --set toolkit.env[1].value=/run/containerd/containerd.sock \
    --set toolkit.env[2].name=CONTAINERD_RUNTIME_CLASS \
    --set toolkit.env[2].value=nvidia \
    --set toolkit.env[3].name=CONTAINERD_SET_AS_DEFAULT \
    --set toolkit.env[3].value=true
```

I fixed it by changing the values.yaml file directly in such a manner:

```
toolkit:
  repository: artifactory.raiffeisen.ru/cibms-docker/nvidia/nvcr.io/nvidia/k8s
  image: container-toolkit
  version: 1.4.7-ubuntu18.04
  imagePullPolicy: IfNotPresent
  imagePullSecrets: []
# START changes
  env:
    - name: CONTAINERD_CONFIG
      value: "/etc/containerd/config.toml"
    - name: CONTAINERD_SOCKET
      value: "/run/containerd/containerd.sock"
    - name: CONTAINERD_RUNTIME_CLASS
      value: "nvidia"
    - name: CONTAINERD_SET_AS_DEFAULT
      value: "true"
# END OF CHANGES
  tolerations:
  - key: nvidia.com/gpu
    operator: Exists
    effect: NoSchedule
  nodeSelector:
    nvidia.com/gpu.deploy.container-toolkit: "true"
  affinity: {}
  podSecurityContext: {}
  securityContext:
    privileged: true
    seLinuxOptions:
      level: "s0"
  resources: {}
  priorityClassName: system-node-critical
```
It's working confguration.

I tried also
```
    - name: CONTAINERD_SET_AS_DEFAULT
      value: true
```
and it didn't work too.
I believe that there is issue with quoting somewhere in helm chart.
