### ISSUE TITLE
driver compilation error

### ISSUE THREAD

**Issue by rhysjtevans** [NVIDIA/gpu-operator#210]
_The template below is mostly useful for bug reports and support questions. Feel free to remove anything which doesn't apply to you and add more information where it makes sense._

### 1. Quick Debug Checklist
- [ ] Are you running on an Ubuntu 18.04 node?
- [X] Are you running Kubernetes v1.13+?
- [ ] Are you running Docker (>= 18.06) or CRIO (>= 1.13+)? Containerd
- [ ] Do you have `i2c_core` and `ipmi_msghandler` loaded on the nodes?
- [X] Did you apply the CRD (`kubectl describe clusterpolicies --all-namespaces`)

### 1. Issue or feature description
nvidia driver daemonset pod fails to compile the nvidia driver.


### 2. Steps to reproduce the issue
Deployed the gpu-operator (helm chart v1.7.0) with the following values file with aws centos8.3 ami based kubernetes cluster.
`uname -a`
`Linux linux-worker-0 4.18.0-305.3.1.el8.x86_64`

```
psp:
  enabled: "true"
devicePlugin:
  repository: "fqdn/nvidia"
gfd:
  repository: "fqdn/nvidia"
migManager:
  repository: "fqdn/nvidia/cloud-native"
dcgmExporter:
  repository: "fqdn/nvidia/k8s"
driver:
  repository: "fqdn/nvidia"
  version: "450.80.02"
  repoConfig:
    configMapName: repo-config
    destinationDir: /etc/yum.repos.d
validator:
  repository: "fqdn/nvidia/cloud-native"
  version: "v1.7.1"
operator:
  defaultRuntime: containerd
  repository: "fqdn/nvidia"
  version: "v1.7.1"
toolkit:
  repository: "fqdn/nvidia/k8s"
  env:
  - name: CONTAINERD_CONFIG
    value: /etc/containerd/config.toml
  - name: CONTAINERD_SOCKET
    value: /run/containerd/containerd.sock
  - name: CONTAINERD_RUNTIME_CLASS
    value: nvidia
  - name: CONTAINERD_SET_AS_DEFAULT
    value: "true"
```

UPDATED:
Stack trace:
```
Checking NVIDIA driver packages...
  Updating the package cache...
  Resolving Linux kernel version...
  Proceeding with Linux kernel version 4.18.0-305.7.1.el8_4.x86_64
  Installing elfutils...
  Installing Linux kernel headers...
  Installing Linux kernel module files...
  Generating Linux kernel version string for 4.18.0-305.7.1.el8_4.x86_64...
  Compiling NVIDIA driver kernel modules...
  Unable to open the file '/lib/modules/4.18.0-305.7.1.el8_4.x86_64/proc/version' (No such file or directory)./usr/src/nvidia-450.80.02/kernel/nvidia-drm/nvidia-drm-gem-user-memory.c: In function '__nv_drm_gem_user_memory_prime_get_sg_table':
  /usr/src/nvidia-450.80.02/kernel/nvidia-drm/nvidia-drm-gem-user-memory.c:63:48: error: passing argument 1 of 'drm_prime_pages_to_sg' from incompatible pointer type [-Werror=incompatible-pointer-types]
       return drm_prime_pages_to_sg(nv_user_memory->pages,
                                    ~~~~~~~~~~~~~~^~~~~~~
  In file included from /usr/src/nvidia-450.80.02/kernel/nvidia-drm/nvidia-drm-gem-user-memory.c:28:
  ./include/drm/drm_prime.h:91:18: note: expected 'struct drm_device *' but argument is of type 'struct page **'
   struct sg_table *drm_prime_pages_to_sg(struct drm_device *dev,
                    ^~~~~~~~~~~~~~~~~~~~~
  /usr/src/nvidia-450.80.02/kernel/nvidia-drm/nvidia-drm-gem-user-memory.c:64:48: warning: passing argument 2 of 'drm_prime_pages_to_sg' makes pointer from integer without a cast [-Wint-conversion]
                                    nv_user_memory->pages_count);
                                    ~~~~~~~~~~~~~~^~~~~~~~~~~~~
  In file included from /usr/src/nvidia-450.80.02/kernel/nvidia-drm/nvidia-drm-gem-user-memory.c:28:
  ./include/drm/drm_prime.h:91:18: note: expected 'struct page **' but argument is of type 'long unsigned int'
   struct sg_table *drm_prime_pages_to_sg(struct drm_device *dev,
                    ^~~~~~~~~~~~~~~~~~~~~
  /usr/src/nvidia-450.80.02/kernel/nvidia-drm/nvidia-drm-gem-user-memory.c:63:12: error: too few arguments to function 'drm_prime_pages_to_sg'
       return drm_prime_pages_to_sg(nv_user_memory->pages,
              ^~~~~~~~~~~~~~~~~~~~~
  In file included from /usr/src/nvidia-450.80.02/kernel/nvidia-drm/nvidia-drm-gem-user-memory.c:28:
  ./include/drm/drm_prime.h:91:18: note: declared here
   struct sg_table *drm_prime_pages_to_sg(struct drm_device *dev,
                    ^~~~~~~~~~~~~~~~~~~~~
  /usr/src/nvidia-450.80.02/kernel/nvidia-drm/nvidia-drm-gem-user-memory.c:65:1: warning: control reaches end of non-void function [-Wreturn-type]
   }
   ^
  cc1: some warnings being treated as errors
  make[2]: *** [scripts/Makefile.build:315: /usr/src/nvidia-450.80.02/kernel/nvidia-drm/nvidia-drm-gem-user-memory.o] Error 1
  make[2]: *** Waiting for unfinished jobs....
  make[1]: *** [Makefile:1563: _module_/usr/src/nvidia-450.80.02/kernel] Error 2
  make: *** [Makefile:81: modules] Error 2
  Stopping NVIDIA persistence daemon...
  Unloading NVIDIA driver kernel modules...
  Unmounting NVIDIA driver rootfs...
  stream closed                                                                                                                                                                                                                                    ```
