### ISSUE TITLE
Confirm the usage of GPU operator

### ISSUE THREAD

**Issue by Kaka1127** [NVIDIA/gpu-operator#214]
Hi Community member,

Please let me confirm the following questions.

1. Regarding to the following documents, it said that we could change the mig profile by editting the label on node.
[GPU Operator with MIG — NVIDIA Cloud Native Technologies documentation](https://docs.nvidia.com/datacenter/cloud-native/gpu-operator/gpu-operator-mig.html)
   In case of using the mixed strategy, how we add the label for nodes?
   i.e. If we would like to configure the mig profile like below, how should we do?
         Example:  One server has two A100 cards.
                          One A100 card:
                          - 1g.5gb: 2
                          - 2g.10gb: 1
                          - 3g.20gb: 1
                          Other A100 card:
                           - 7g.40gb:1

2. In case of using the GPU operator, does it work correctly even though running the DCGM exporters on GPU node?

Best regards.
Kaka

**Comment by Kaka1127** [comment]
I found that the mig profile was register on "ConfigMap". So, I am waiting for answer against for No.2.

**Comment by kpouget** [comment]
Hello @Kaka1127, yes [this ConfigMap](https://github.com/NVIDIA/gpu-operator/blob/master/assets/state-mig-manager/0400_configmap.yaml) is where you can add custom MIG configurations.

Could you share the entry you added there, just for the record?

for 2/, my (unofficial) answer is that it should work, DCGM supports MIG slicing, but I didn't really test it myself

**Comment by Kaka1127** [comment]
Hi kpouget

Thank you for your response.
Here is my configmap file.
```
version: v1
mig-configs:
  all-disabled:
    - devices: all
      mig-enabled: false

  # A100-40GB
  all-1g.5gb:
    - devices: all
      mig-enabled: true
      mig-devices:
        "1g.5gb": 7

  all-2g.10gb:
    - devices: all
      mig-enabled: true
      mig-devices:
        "2g.10gb": 3

  all-3g.20gb:
    - devices: all
      mig-enabled: true
      mig-devices:
        "3g.20gb": 2

  all-7g.40gb:
    - devices: all
      mig-enabled: true
      mig-devices:
        "7g.40gb": 1

  # A100-80GB
  all-1g.10gb:
    - devices: all
      mig-enabled: true
      mig-devices:
        "1g.10gb": 7

  all-2g.20gb:
    - devices: all
      mig-enabled: true
      mig-devices:
        "2g.20gb": 3

  all-3g.40gb:
    - devices: all
      mig-enabled: true
      mig-devices:
        "3g.40gb": 2

  all-7g.80gb:
    - devices: all
      mig-enabled: true
      mig-devices:
        "7g.80gb": 1

  # A30-24GB
  all-1g.6gb:
    - devices: all
      mig-enabled: true
      mig-devices:
        "1g.6gb": 4

  all-2g.12gb:
    - devices: all
      mig-enabled: true
      mig-devices:
        "2g.12gb": 2

  all-4g.24gb:
    - devices: all
      mig-enabled: true
      mig-devices:
        "4g.24gb": 1

  all-balanced:
    # A100-40GB
    - devices: all
      mig-enabled: true
      mig-devices:
        "1g.5gb": 2
        "2g.10gb": 1
        "3g.20gb": 1

  optimaize:
    # A100-40GB
    - devices: [0]
      mig-enabled: true
      mig-devices:
        "1g.5gb": 2
        "2g.10gb": 1
        "3g.20gb": 1
    - devices: [1]
      mig-enabled: false
```

For No.2, we will check it after my main verification task.
