### ISSUE TITLE
Question: label to disable GPU schedulling on a node

### ISSUE THREAD

**Issue by xhejtman** [NVIDIA/gpu-operator#237]
Hello,

is there any label that could be used to prevent schedule GPU jobs to a node? I think nvidia.com/gpu.deploy.device-plugin: "false" can be used for this but I am not sure how persistent is this? Is there any other label that could 'reserve' GPUs on a node?

**Comment by shivamerla** [comment]
@xhejtman  you can taint the node with `nvidia.com/gpu=true:NoSchedule` and only pods with explicit toleration can run on that node. By default all GPU operator pods have this toleration.

```
  tolerations:
  - key: nvidia.com/gpu
    operator: Exists
    effect: NoSchedule
```
