### ISSUE TITLE
Containerd K3S operator

### ISSUE THREAD

**Issue by wstarzak** [NVIDIA/gpu-operator#238]
_The template below is mostly useful for bug reports and support questions. Feel free to remove anything which doesn't apply to you and add more information where it makes sense._

### 1. Quick Debug Checklist
- [ ] Are you running on an Ubuntu 18.04 node?
- [x ] Are you running Kubernetes v1.13+?
- [ ] Are you running Docker (>= 18.06) or CRIO (>= 1.13+)?
- [ ] Do you have `i2c_core` and `ipmi_msghandler` loaded on the nodes?
- [x ] Did you apply the CRD (`kubectl describe clusterpolicies --all-namespaces`)

### 1. Issue or feature description

The containerd support is present but since k3s is templating it it looks like its not starting up. I have created tmpl according to k3s documentation for containerd and pointed sock to the valid path.

`    - name: CONTAINERD_SOCKET
      value: /run/k3s/containerd/containerd.sock
    - name: CONTAINERD_CONFIG
      value: /var/lib/rancher/k3s/agent/etc/containerd/config.toml
    - name: CONTAINERD_SET_AS_DEFAULT
      value: "true"
`

`[plugins.cri]
  enable_selinux = false
  sandbox_image = "docker.io/rancher/pause:3.1"
  stream_server_address = "127.0.0.1"
  stream_server_port = "10010"

  [plugins.cri.cni]
    bin_dir = "{{ .NodeConfig.AgentConfig.CNIBinDir }}"
    conf_dir = "{{ .NodeConfig.AgentConfig.CNIConfDir }}"

  [plugins.cri.containerd]
    disable_snapshot_annotations = true
    snapshotter = "overlayfs"

    [plugins.cri.containerd.runtimes]

      [plugins.cri.containerd.runtimes.nvidia]
        privileged_without_host_devices = false
        runtime_engine = ""
        runtime_root = ""
        runtime_type = "io.containerd.runc.v2"

      [plugins.cri.containerd.runtimes.nvidia.options]
        BinaryName = "/usr/local/nvidia/toolkit/nvidia-container-runtime"

      [plugins.cri.containerd.runtimes.runc]
        runtime_type = "io.containerd.runc.v2"

[plugins.opt]
  path = "/var/lib/rancher/k3s/agent/containerd"
`

I do get:
`MountVolume.SetUp failed for volume "nvidia-operator-validator-token-9dbxf" : failed to sync secret cache: timed out waiting for the condition`
from the operator validator and i cant see present devices in /dev, rest of the pods are running ok. 

### 2. Steps to reproduce the issue

1. Install fres k3s with containerd
2. Install GPU operator with values provided above.

### 3. Information to [attach](https://help.github.com/articles/file-attachments-on-issues-and-pull-requests/) (optional if deemed irrelevant)

 - [ ] kubernetes pods status: `kubectl get pods --all-namespaces`
 - [ ] kubernetes daemonset status: `kubectl get ds --all-namespaces`
 - [ ] If a pod/ds is in an error state or pending state `kubectl describe pod -n NAMESPACE POD_NAME`
 - [ ] If a pod/ds is in an error state or pending state `kubectl logs -n NAMESPACE POD_NAME`

 - [ ] Output of running a container on the GPU machine: `docker run -it alpine echo foo`
 - [ ] Docker configuration file: `cat /etc/docker/daemon.json`
 - [ ] Docker runtime configuration: `docker info | grep runtime`

 - [ x] NVIDIA shared directory: `ls -la /run/nvidia`
 - [ x] NVIDIA packages directory: `ls -la /usr/local/nvidia/toolkit`
 - [ x] NVIDIA driver directory: `ls -la /run/nvidia/driver`
 - [ ] kubelet logs `journalctl -u kubelet > kubelet.logs`
[lsfiles.txt](https://github.com/NVIDIA/gpu-operator/files/6960225/lsfiles.txt)

**Comment by shivamerla** [comment]
@wstarzak  can you attach output of `kubectl describe pod <operator-validator-pod-name> -n gpu-operator-resources` and also logs from failing initContainer `kubectl logs <operator-validator-pod-name> -c <init-container-name> -n gpu-operator-resources`. All other pods are running fine? Can you paste the output of `kubectl get pods -n gpu-operator-resources`?

**Comment by maxirus** [comment]
I was "sorta" able to get this to work...

### Environment:
OS: Ubuntu 20.04.3 LTS (5.4.0-91-generic)
Kubernetes: K3s v1.22.3+k3s1
Containerd: 1.5.7-k3s2
GPU: P620

### Steps taken

#### 1. Verify NVIDIA device

After a lot of frustration, I discovered the GPU wasn't listed in `lspci`. I would suggest as a first step to make sure the node shows your NVIDIA card by running `lspci | grep NVIDIA`. 

> NOTE: In my particular case, using a Lenovo P340 Tiny, I had to have the VGA Mode set to `Auto` in the BIOS.

#### 2. Disable Nouveau

Disable Nouveau on the GPU node. Follow the docs [here](https://docs.nvidia.com/cuda/cuda-installation-guide-linux/index.html#runfile-nouveau-ubuntu).

> NOTE: I didn't see this called out in the Operator docs any more so this may no longer be needed

#### 3. Install Drivers

I could not get the install driver functionality of the Helm Chart/Operator to work. I suspect it only supports the Enterprise/Datacenter GPUs. I imagine this could be customized to install the appropriate drivers for my GPU but for me it was easier to simply install the drivers manually. To do this, run:

```bash
apt-get update && \
apt-get install nvidia-headless-470-server nvidia-utils-470-server
```

> NOTE: 470 was the latest as of this writing. Check for the latest by running `apt-get search nvidia-driver`

#### 4. Install Operator

Install the Operator via the Helm Chart. You can mostly follow the directions [here](https://docs.nvidia.com/datacenter/cloud-native/gpu-operator/getting-started.html#install-the-gpu-operator) but use the following Helm values:
```yaml
dcgm:
  enabled: false
migManager:
  enabled: false
driver:
  enabled: false
toolkit:
  enabled: true
  env:
    - name: CONTAINERD_CONFIG
      value: /var/lib/rancher/k3s/agent/etc/containerd/config.toml
    - name: CONTAINERD_SOCKET
      value: /run/k3s/containerd/containerd.sock
    - name: CONTAINERD_RUNTIME_CLASS
      value: nvidia
    - name: CONTAINERD_SET_AS_DEFAULT
      value: "true"
```

For me, I needed to disable the Datacenter features of `dcgm` and `migManager` as I am not using a DC GPU. You need to override the default containerd values as k3s installs these in a non-default location. By doing this, I noticed my `/var/lib/rancher/k3s/agent/etc/containerd/config.toml` was updated with:

```toml
[plugins.cri.containerd.runtimes."nvidia"]
  runtime_type = "io.containerd.runc.v2"
[plugins.cri.containerd.runtimes."nvidia".options]
  BinaryName = "/usr/local/nvidia/toolkit/nvidia-container-runtime"

[plugins.cri.containerd.runtimes."nvidia-experimental"]
  runtime_type = "io.containerd.runc.v2"
[plugins.cri.containerd.runtimes."nvidia-experimental".options]
  BinaryName = "/usr/local/nvidia/toolkit/nvidia-container-runtime-experimental"
```

This is a bit different than what the [Docs](https://docs.nvidia.com/datacenter/cloud-native/gpu-operator/getting-started.html#bare-metal-passthrough-with-pre-installed-drivers-and-nvidia-container-toolkit) say and is what got me hung-up.

#### 5. Test

After a bit of time, the Pods eventually go all green. Now here's where the "sorta" comes in... I tried running the test Pod described [here](https://docs.nvidia.com/datacenter/cloud-native/gpu-operator/getting-started.html#cuda-vectoradd) but I got the error: `Failed to allocate device vector A (error code CUDA driver version is insufficient for CUDA runtime version)!`. 

I then tried running the below Pod:
```yaml
apiVersion: v1
kind: Pod
metadata:
  name: gpu-test
spec:
  restartPolicy: Never
  containers:
    - name: gpu
      image: "nvidia/cuda:11.4.1-base-ubuntu20.04"
      command: [ "/bin/bash", "-c", "--" ]
      args: [ "while true; do sleep 30; done;" ]
      resources:
        limits:
          nvidia.com/gpu: 1
```
exec'd into the Pod, installed nvidia-utils (`apt install nvidia-utils-470-server`), and ran `nvidia-smi` which gave me the following:

```bash
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 470.82.01    Driver Version: 470.82.01    CUDA Version: 11.4     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Quadro P620         Off  | 00000000:02:00.0 Off |                  N/A |
| 34%   35C    P8    N/A /  N/A |      0MiB /  2000MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+
```

I *believe* by running this command in the container and that it shows the NVIDIA GPU, it means it's working.
