### ISSUE TITLE
Configure a proxy for nvidia-driver

### ISSUE THREAD

**Issue by creydr** [NVIDIA/gpu-operator#25]
### 1. Quick Debug Checklist
- [x] Are you running on an Ubuntu 18.04 node?
- [x] Are you running Kubernetes v1.13+?
- [x] Are you running Docker (>= 18.06) or CRIO (>= 1.13+)?
- [x] Do you have `i2c_core` and `ipmi_msghandler` loaded on the nodes?
- [x] Did you apply the CRD (`kubectl describe specialresources --all-namespaces`)

### 1. Issue or feature description
When the operator is deployed in an environment without direct internet access, the nvidia-driver fails to download the nvidia kernel modules (e.g. for the [ubuntu image](https://gitlab.com/nvidia/container-images/driver/blob/master/ubuntu18.04/Dockerfile) they are [downloaded](https://gitlab.com/nvidia/container-images/driver/blob/master/ubuntu18.04/nvidia-driver#L279) from the official ubuntu mirror). 
Is it possible to configure a proxy for the nvidia-driver-daemonset?

### 2. Steps to reproduce the issue
Deploy the operator in an environment where internet access is only given through a proxy.

Thanks for your help

**Comment by RenaudWasTaken** [comment]
Hello!

How do you usually proxy the HTTP traffic in your kubernetes cluster ?
You could try to do the same for the GPU Operator.

**Comment by creydr** [comment]
Hi,
usually the proxy is configured inside the pod if required. But this does not work in this case, because the pod comes from the operator (via the nvidia-driver-daemonset) and can't be configured/patched e.g. via kustomize. At least I did not find a way yet.

**Comment by nvjmayo** [comment]
What if we accepted an environment variable that lets you change the mirror used for /etc/apt/sources.list ? 

technically you could direct all internet traffic to your own http mirror as a work around. but I think I'd rather allow tweaking of the containers that operator deploys.

**Comment by creydr** [comment]
Hello,
this would be great.

**Comment by alexandrem** [comment]
Looking for this functionality as well.

**Comment by rspierz** [comment]
I've added proxy settings in env vars yaml of "nvidia-driver-daemonset" as a workaround. Although if the operator updates this will get overwritten so It would be great to have the ClusterPolicy support proxy in the config or have it respect the cluster wide proxy at "oc get proxy"

**Comment by jtcarnes** [comment]
I have the same issue. Working with GPU operator behind a corporate proxy. As stated, we normally can inject them into the pods with env, but because we dont have access to the pod definitions (they come from the operator), we are hitting a roadblock. It would be nice if, on top of the options currently exposed for the driver, env would be added.

**Comment by shivamerla** [comment]
This will be addressed in the upcoming release with this change: https://gitlab.com/nvidia/kubernetes/gpu-operator/-/merge_requests/140

**Comment by brandor5** [comment]
Any updates on this being merged?

**Comment by shivamerla** [comment]
@brandor5 Yes, that change has been merged, but official helm charts/gpu-operator images will be available with next release early/mid December. Until then, you can try it out to build private image and install chart from source repo.

**Comment by shivamerla** [comment]
1.4.0 chart is now available, where ENV can be setup with all components for proxy settings.

**Comment by 3ch01c** [comment]
In case it wasn't obvious to anyone else...

```yaml
# proxy-vars.yml
---
driver:
  env:
    - name: http_proxy
      value: http://proxyout.example.com
    - name: https_proxy
      value: http://proxyout.example.com
toolkit:
  env:
    - name: http_proxy
      value: http://proxyout.example.com
    - name: https_proxy
      value: http://proxyout.example.com
devicePlugin:
  env:
    - name: http_proxy
      value: http://proxyout.example.com
    - name: https_proxy
      value: http://proxyout.example.com
dcgmExporter:
  env:
    - name: http_proxy
      value: http://proxyout.example.com
    - name: https_proxy
      value: http://proxyout.example.com
gfd:
  env:
    - name: http_proxy
      value: http://proxyout.example.com
    - name: https_proxy
      value: http://proxyout.example.com
```

```sh
helm install -f proxy-vars.yml gpu-operator nvidia/gpu-operator
```
