### ISSUE TITLE
nvidia-cuda-validator pods crashlooping in OpenShift 4.6

### ISSUE THREAD

**Issue by koflerm** [NVIDIA/gpu-operator#253]
Today we updated the GPU operator in one of our OpenShift clusters (Version 4.6.35) to the version 1.7.1. The upgrade included uninstalling the old GPU operator version and installing everything from scratch. After the update however, the nvidia-cuda-validator pods are crashing with the error "Failed to allocate device vector A (error code no CUDA-capable device is detected)!" in the cuda-validation init container. All other parts are running fine. The ClusterPolicy on our side looks like this:

```
apiVersion: nvidia.com/v1
kind: ClusterPolicy
metadata:
  name: gpu-cluster-policy
spec:
  dcgmExporter:
    repository: dockerregistry.site.example.com/nvidia
    version: "2.1.8-2.4.0-rc.2-ubi8"
    image: dcgm-exporter
    nodeSelector:
      nvidia.com/gpu.deploy.dcgm-exporter: 'true'
  devicePlugin:
    repository: dockerregistry.site.example.com/nvidia
    version: v0.9.0-ubi8
    image: k8s-device-plugin
    nodeSelector:
      nvidia.com/gpu.deploy.device-plugin: 'true'
    env:
      - name: PASS_DEVICE_SPECS
        value: "true"
      - name: FAIL_ON_INIT_ERROR
        value: "true"
      - name: DEVICE_LIST_STRATEGY
        value: "volume-mounts"
      - name: DEVICE_ID_STRATEGY
        value: "uuid"
      - name: NVIDIA_VISIBLE_DEVICES
        value: "all"
      - name: NVIDIA_DRIVER_CAPABILITIES
        value: "all"
  driver:
    repository: dockerregistry.site.example.com/nvidia
    version: 460.73.01
    image: driver
    nodeSelector:
      nvidia.com/gpu.deploy.driver: 'true'
    # attention - the version field for the driver must be fefined without the -rhcos4.6 suffix
  gfd:
    repository: dockerregistry.site.example.com/nvidia
    version: v0.4.1
    image: gpu-feature-discovery
    nodeSelector:
      nvidia.com/gpu.deploy.gpu-feature-discovery: 'true'
    env:
      - name: GFD_SLEEP_INTERVAL
        value: "60s" 
      - name: FAIL_ON_INIT_ERROR
        value: "true"       
  operator:
    defaultRuntime: crio
    deployGFD: true
    initContainer:
      image: cuda
      repository: dockerregistry.site.example.com/nvidia
      version: 11.4.0-base-ubi8
  validator:
    image: gpu-operator-validator
    repository: dockerregistry.site.example.com/nvidia
    version: v1.7.1
    nodeSelector:
      nvidia.com/gpu.deploy.operator-validator: 'true'
    env:
      - name: WITH_WORKLOAD
        value: "true"
  mig:
    strategy: mixed
  migManager:
    repository: dockerregistry.site.example.com/nvidia
    version: v0.1.0-ubi8
    image: k8s-mig-manager
    nodeSelector:
      nvidia.com/gpu.deploy.mig-manager: 'true'
    env:
      - name: WITH_REBOOT
        value: "false"
  toolkit:
    repository: dockerregistry.site.example.com/nvidia
    version: 1.5.0-ubi8
    image: container-toolkit
    nodeSelector:
    nvidia.com/gpu.deploy.container-toolkit: 'true'
```

Can you please help us with this issue?

**Comment by shivamerla** [comment]
@koflerm Is the issue still persistent? Both plugin validation and cuda validation use same `vectorAdd` sample, wondering why once succeeded and other failed.

**Comment by koflerm** [comment]
@shivamerla Yes the problem is still existing. Actually I think the plugin validation was not yet started because also because of the crashing cuda-validator pods the nvidia-operator-validator which includes the plugin-validation as the 4th init container has not started this init container because it is still waiting for the 2nd init container to finish (which waits for the successful start of the cuda-validator pods)

**Comment by shivamerla** [comment]
@koflerm can you copy output of `nvidia-smi` run from any of the pods(plugin, gfd etc)? Also, if you can run this test pod and verify if the necessary files are injected by toolkit. It will be looping in the init container so we can run below commands.

```
cat << EOF | kubectl create -f -
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: nvidia-cuda-validator
  generateName: nvidia-cuda-validator-
  namespace: gpu-operator-resources
spec:
  tolerations:
    - key: nvidia.com/gpu
      operator: Exists
      effect: NoSchedule
  restartPolicy: Never
  serviceAccount: nvidia-operator-validator
  initContainers:
  - name: cuda-validation
    image: nvcr.io/nvidia/cloud-native/gpu-operator-validator:v1.7.1
    imagePullPolicy: IfNotPresent
    command: ['sh', '-c']
    args: ["vectorAdd && sleep inf"]
    securityContext:
      allowPrivilegeEscalation: false
  containers:
    - name: nvidia-cuda-validator
      image: nvcr.io/nvidia/cloud-native/gpu-operator-validator:v1.7.1
      imagePullPolicy: IfNotPresent
      # override command and args as validation is already done by initContainer
      command: ['sh', '-c']
      args: ["echo cuda workload validation is successful && sleep inf"]
      securityContext:
        allowPrivilegeEscalation: false
EOF
```

```
oc exec <pod-name> -n gpu-operator-resources -c cuda-validation -- ls -l /dev/nvidia*
oc exec <pod-name> -n gpu-operator-resources -c cuda-validation -- ls -l /lib64 | egrep -i "cuda|libnvidia"
``
