### ISSUE TITLE
Unable to persist proxy settings within nvidia-driver-daemonset

### ISSUE THREAD

**Issue by denniskaulbars** [NVIDIA/gpu-operator#260]
### 1. Quick Debug Checklist
- [x] Are you running on an Ubuntu 18.04 node? No
- [x] Are you running Kubernetes v1.13+? Yes. v1.20
- [x] Are you running Docker (>= 18.06) or CRIO (>= 1.13+)? CRIO

### 1. Issue or feature description
Within an Redhat OpenShift 4.7 cluster in an air-gapped environment, we want to use the NVIDIA GPU operator 1.80 to provide GPU support for our cluster. We want to use the operator from the Operator Hub, not from Helm.

During installation, we are facing an issue that we are unable to persist the proxy settings for the nvidia-driver-daemonset.
Without proxy support, the daemonset hangs at the 

```
+ echo 'Updating the package cache...'
+ yum -q makecache
```

We tried to modify the cluster policy in order to set the corresponding environment variables:

```
apiVersion: nvidia.com/v1
kind: ClusterPolicy
spec:
  migManager:
    enabled: true
    env:
      - name: WITH_REBOOT
        value: 'false'
    image: k8s-mig-manager
    imagePullSecrets: []
    repository: nvcr.io/nvidia/cloud-native
    resources: {}
    securityContext: {}
    version: 'sha256:77b8e58a54c222bee3cc56b2305d4cebfa60722c122858f94301e611f87d7fec'
  operator:
    defaultRuntime: crio
    initContainer:
      image: cuda
      imagePullSecrets: []
      repository: nvcr.io/nvidia
      version: 'sha256:15674e5c45c97994bc92387bad03a0d52d7c1e983709c471c4fecc8e806dbdce'
    runtimeClass: nvidia
  dcgm:
    enabled: true
    hostPort: 5555
    image: dcgm
    imagePullSecrets: []
    repository: nvcr.io/nvidia/cloud-native
    resources: {}
    securityContext: {}
    version: 'sha256:28f334d6d5ca6e5cad2cf05a255989834128c952e3c181e6861bd033476d4b2c'
  gfd:
    env:
      - name: GFD_SLEEP_INTERVAL
        value: 60s
      - name: FAIL_ON_INIT_ERROR
        value: 'true'
    image: gpu-feature-discovery
    imagePullSecrets: []
    repository: nvcr.io/nvidia
    resources: {}
    securityContext: {}
    version: 'sha256:bfc39d23568458dfd50c0c5323b6d42bdcd038c420fb2a2becd513a3ed3be27f'
  dcgmExporter:
    config:
      name: ''
    env:
      - name: DCGM_EXPORTER_LISTEN
        value: ':9400'
      - name: DCGM_EXPORTER_KUBERNETES
        value: 'true'
      - name: DCGM_EXPORTER_COLLECTORS
        value: /etc/dcgm-exporter/dcp-metrics-included.csv
    image: dcgm-exporter
    imagePullSecrets: []
    repository: nvcr.io/nvidia/k8s
    resources: {}
    securityContext: {}
    version: 'sha256:e37404194fa2bc2275827411049422b93d1493991fb925957f170b4b842846ff'
  driver:
    licensingConfig:
      configMapName: ''
    enabled: true
    imagePullSecrets: []
    resources: {}
    rdma:
      enabled: false
    repository: nvcr.io/nvidia
    manager:
      env:
        - name: DRAIN_USE_FORCE
          value: 'false'
        - name: DRAIN_POD_SELECTOR_LABEL
          value: ''
        - name: DRAIN_TIMEOUT_SECONDS
          value: 0s
        - name: DRAIN_DELETE_EMPTYDIR_DATA
          value: 'false'
        - name: HTTPS_PROXY
          value: 'http://xxxxx:xxxx'
        - name: HTTP_PROXY
          value: 'http://xxxxx:xxxx'
        - name: https_proxy
          value: 'http://xxxxx:xxxx'
        - name: http_proxy
          value: 'http://xxxxx:xxxx'
      image: k8s-driver-manager
      imagePullSecrets: []
      repository: nvcr.io/nvidia/cloud-native
      version: 'sha256:907ab0fc008bb90149ed059ac3a8ed3d19ae010d52c58c0ddbafce45df468d5b'
    securityContext: {}
    repoConfig:
      configMapName: ''
      destinationDir: ''
    version: 'sha256:a62de5e843a41c65cf837e7db5f5b675d03fa2de05e981a859b114336cf183e3'
    virtualTopology:
      config: ''
    image: driver
  devicePlugin:
    args: []
    env:
      - name: PASS_DEVICE_SPECS
        value: 'true'
      - name: FAIL_ON_INIT_ERROR
        value: 'true'
      - name: DEVICE_LIST_STRATEGY
        value: envvar
      - name: DEVICE_ID_STRATEGY
        value: uuid
      - name: NVIDIA_VISIBLE_DEVICES
        value: all
      - name: NVIDIA_DRIVER_CAPABILITIES
        value: all
    image: k8s-device-plugin
    imagePullSecrets: []
    repository: nvcr.io/nvidia
    resources: {}
    securityContext: {}
    version: 'sha256:85def0197f388e5e336b1ab0dbec350816c40108a58af946baa1315f4c96ee05'
  mig:
    strategy: single
  validator:
    env:
      - name: WITH_WORKLOAD
        value: 'true'
    image: gpu-operator-validator
    imagePullSecrets: []
    repository: nvcr.io/nvidia/cloud-native
    resources: {}
    securityContext: {}
    version: 'sha256:1cce434a1722288bacab5eaa5c194ca2bdbad55679ba871a2814556853339585'
  nodeStatusExporter:
    enabled: true
    image: gpu-operator-validator
    imagePullSecrets: []
    repository: nvcr.io/nvidia/cloud-native
    resources: {}
    securityContext: {}
    version: 'sha256:1cce434a1722288bacab5eaa5c194ca2bdbad55679ba871a2814556853339585'
  daemonsets:
    priorityClassName: system-node-critical
    tolerations:
      - effect: NoSchedule
        key: nvidia.com/gpu
        operator: Exists
  toolkit:
    enabled: true
    image: container-toolkit
    imagePullSecrets: []
    repository: nvcr.io/nvidia/k8s
    resources: {}
    securityContext: {}
    version: 'sha256:8f9517b4c83b8730c40134df385088be41519b585176c66727ff6f181ae5e703'
```

Unfortunately, the environment variables are not set within the daemonset:

```
user@HOST$oc rsh nvidia-driver-daemonset-dgj54
Defaulted container "nvidia-driver-ctr" out of: nvidia-driver-ctr, k8s-driver-manager (init)
sh-4.4# env|grep -i proxy
sh-4.4#
```
