### ISSUE TITLE
 Back to the default config file after edit the mig config

### ISSUE THREAD

**Issue by MeranaTona** [NVIDIA/gpu-operator#281]
### 1. Quick Debug Checklist
- [ ] Are you running on an Ubuntu 18.04 node? 20.04 
- [ ] Are you running Kubernetes v1.13+? 1.21
- [ ] Are you running Docker (>= 18.06) or CRIO (>= 1.13+)? Crio 1.21
- [ ] Do you have `i2c_core` and `ipmi_msghandler` loaded on the nodes?
- [ ] Did you apply the CRD (`kubectl describe clusterpolicies --all-namespaces`)

### 1. Issue or feature description
Same problem like here: https://github.com/NVIDIA/gpu-operator/issues/249 but on gpu-operator 1.8.2. The edited config map (for adding new partition options) is replaced by the default configmap after a few seconds. "default-mig-parted-config" is the only configmap in namespace: 
 kubectl get configmaps -n gpu-operator-resources
```
NAME                        DATA   AGE
default-mig-parted-config   1      4d19h
istio-ca-root-cert          1      4d5h
kube-root-ca.crt            1      4d19h
```

### 2. Steps to reproduce the issue
kubectl edit configmap default-mig-parted-config -n gpu-operator-resources

### 3. Information to [attach](https://help.github.com/articles/file-attachments-on-issues-and-pull-requests/) (optional if deemed irrelevant)

 - [ ] kubernetes pods status: `kubectl get pods --all-namespaces`
One deamonset is in crashloop:
kubectl get po -A
```
NAMESPACE                   NAME                                                              READY   STATUS             RESTARTS   AGE
auth                        dex-596f487d76-8mtbv                                              1/1     Running            0          4d
cert-manager                cert-manager-7dd5854bb4-5wpdm                                     1/1     Running            0          4d5h
cert-manager                cert-manager-cainjector-64c949654c-k9qv8                          1/1     Running            2          4d5h
cert-manager                cert-manager-webhook-6b57b9b886-v7hr6                             1/1     Running            2          4d5h
default                     gpu-operator-5f8b7c4f59-bqwqk                                     1/1     Running            0          4d19h
default                     nvidia-gpu-operator-node-feature-discovery-master-74db7c56djx8d   1/1     Running            0          4d19h
default                     nvidia-gpu-operator-node-feature-discovery-worker-8dfpq           1/1     Running            0          4d19h
default                     nvidia-gpu-operator-node-feature-discovery-worker-b9dtr           1/1     Running            0          4d19h
default                     nvidia-gpu-operator-node-feature-discovery-worker-fhl6r           1/1     Running            2          4d19h
default                     nvidia-gpu-operator-node-feature-discovery-worker-hf5vx           1/1     Running            0          4d19h
default                     nvidia-gpu-operator-node-feature-discovery-worker-tx5zv           1/1     Running            0          4d19h
docker                      private-docker-registry-7cc989bf7d-mllqh                          1/1     Running            0          4d6h
gpu-operator-resources      gpu-feature-discovery-27h4l                                       1/1     Running            0          3h18m
gpu-operator-resources      gpu-feature-discovery-5gfff                                       1/1     Running            0          4d19h
gpu-operator-resources      nvidia-container-toolkit-daemonset-8sb4t                          1/1     Running            0          4d19h
gpu-operator-resources      nvidia-container-toolkit-daemonset-jzbdc                          1/1     Running            2          4d19h
gpu-operator-resources      nvidia-cuda-validator-9f5bj                                       0/1     Completed          0          4d19h
gpu-operator-resources      nvidia-cuda-validator-n9j55                                       0/1     Completed          0          3h22m
gpu-operator-resources      nvidia-dcgm-exporter-6pzwz                                        1/1     Running            0          3h18m
gpu-operator-resources      nvidia-dcgm-exporter-xb77m                                        1/1     Running            0          4d19h
gpu-operator-resources      nvidia-dcgm-pkl9p                                                 1/1     Running            0          3h18m
gpu-operator-resources      nvidia-dcgm-vtlgz                                                 1/1     Running            0          4d19h
gpu-operator-resources      nvidia-device-plugin-daemonset-6k6lw                              1/1     Running            0          4d19h
gpu-operator-resources      nvidia-device-plugin-daemonset-wgwds                              0/1     CrashLoopBackOff   43         3h18m
gpu-operator-resources      nvidia-device-plugin-validator-crfsb                              0/1     Completed          0          3h22m
gpu-operator-resources      nvidia-device-plugin-validator-n7z4x                              0/1     Completed          0          4d19h
gpu-operator-resources      nvidia-driver-daemonset-776ls                                     1/1     Running            0          4d19h
gpu-operator-resources      nvidia-driver-daemonset-wh55d                                     1/1     Running            2          4d19h
gpu-operator-resources      nvidia-mig-manager-7ml8g                                          1/1     Running            2          4d19h
gpu-operator-resources      nvidia-mig-manager-vbs5j                                          1/1     Running            0          4d19h
gpu-operator-resources      nvidia-operator-validator-8s2tw                                   1/1     Running            0          3h22m
gpu-operator-resources      nvidia-operator-validator-8vw58                                   1/1     Running            0          4d19h

```
kubectl describe po nvidia-device-plugin-daemonset-wgwds -n gpu-operator-resources
```
Name:                 nvidia-device-plugin-daemonset-wgwds
Namespace:            gpu-operator-resources
Priority:             2000001000
Priority Class Name:  system-node-critical
Node:                 node_name/node_ip
Start Time:           Mon, 22 Nov 2021 12:14:26 +0100
Labels:               app=nvidia-device-plugin-daemonset
                      controller-revision-hash=8b6cbcb7d
                      pod-template-generation=1
Annotations:          cni.projectcalico.org/containerID: 26f06019df28f22b970b4aa63f38b6f44b0c303303fda161c460ceb26e895eb8
                      cni.projectcalico.org/podIP: 192.168.158.245/32
                      cni.projectcalico.org/podIPs: 192.168.158.245/32
Status:               Running
IP:                   192.168.158.245
IPs:
  IP:           192.168.158.245
Controlled By:  DaemonSet/nvidia-device-plugin-daemonset
Init Containers:
  toolkit-validation:
    Container ID:  cri-o://9d4eb0973f3315e1178fb3466ddf30312e0fdf1f74ccd573ca145342a808ee76
    Image:         nvcr.io/nvidia/cloud-native/gpu-operator-validator:v1.8.2
    Image ID:      nvcr.io/nvidia/cloud-native/gpu-operator-validator@sha256:a07fd1c74e3e469ac316d17cf79635173764fdab3b681dbc282027a23dbbe227
    Port:          <none>
    Host Port:     <none>
    Command:
      sh
      -c
    Args:
      until [ -f /run/nvidia/validations/toolkit-ready ]; do echo waiting for nvidia container stack to be setup; sleep 5; done
    State:          Terminated
      Reason:       Completed
      Exit Code:    0
      Started:      Mon, 22 Nov 2021 12:14:28 +0100
      Finished:     Mon, 22 Nov 2021 12:14:28 +0100
    Ready:          True
    Restart Count:  0
    Environment:    <none>
    Mounts:
      /run/nvidia from run-nvidia (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-9zqvd (ro)
Containers:
  nvidia-device-plugin-ctr:
    Container ID:   cri-o://0336451c6ec6bddb5ed5a750668369d7575113d78d0aa53c5b9a1dc74001d89e
    Image:          nvcr.io/nvidia/k8s-device-plugin:v0.9.0-ubi8
    Image ID:       nvcr.io/nvidia/k8s-device-plugin@sha256:85def0197f388e5e336b1ab0dbec350816c40108a58af946baa1315f4c96ee05
    Port:           <none>
    Host Port:      <none>
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       Error
      Exit Code:    2
      Started:      Mon, 22 Nov 2021 15:29:55 +0100
      Finished:     Mon, 22 Nov 2021 15:29:55 +0100
    Ready:          False
    Restart Count:  43
    Environment:
      PASS_DEVICE_SPECS:           true
      FAIL_ON_INIT_ERROR:          true
      DEVICE_LIST_STRATEGY:        envvar
      DEVICE_ID_STRATEGY:          uuid
      NVIDIA_VISIBLE_DEVICES:      all
      NVIDIA_DRIVER_CAPABILITIES:  all
      NVIDIA_DRIVER_ROOT:          /run/nvidia/driver
      MIG_STRATEGY:                mixed
      NVIDIA_MIG_MONITOR_DEVICES:  all
    Mounts:
      /var/lib/kubelet/device-plugins from device-plugin (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-9zqvd (ro)
Conditions:
  Type              Status
  Initialized       True
  Ready             False
  ContainersReady   False
  PodScheduled      True
Volumes:
  device-plugin:
    Type:          HostPath (bare host directory volume)
    Path:          /var/lib/kubelet/device-plugins
    HostPathType:
  run-nvidia:
    Type:          HostPath (bare host directory volume)
    Path:          /run/nvidia
    HostPathType:  Directory
  kube-api-access-9zqvd:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  3607
    ConfigMapName:           kube-root-ca.crt
    ConfigMapOptional:       <nil>
    DownwardAPI:             true
QoS Class:                   BestEffort
Node-Selectors:              nvidia.com/gpu.deploy.device-plugin=true
Tolerations:                 node.kubernetes.io/disk-pressure:NoSchedule op=Exists
                             node.kubernetes.io/memory-pressure:NoSchedule op=Exists
                             node.kubernetes.io/not-ready:NoExecute op=Exists
                             node.kubernetes.io/pid-pressure:NoSchedule op=Exists
                             node.kubernetes.io/unreachable:NoExecute op=Exists
                             node.kubernetes.io/unschedulable:NoSchedule op=Exists
                             nvidia.com/gpu:NoSchedule op=Exists
Events:
  Type     Reason   Age                    From     Message
  ----     ------   ----                   ----     -------
  Normal   Pulled   15m (x42 over 3h20m)   kubelet  Container image "nvcr.io/nvidia/k8s-device-plugin:v0.9.0-ubi8" already present on machine
  Warning  BackOff  19s (x920 over 3h20m)  kubelet  Back-off restarting failed container
```

Thank you in advance.

**Comment by MeranaTona** [comment]
"One deamonset is in crashloop": I also did "kubectl drain node" beforehand. Might be related

**Comment by shivamerla** [comment]
@MeranaTona if you want to provide custom config map, please pass option `--set migManager.config.name=<custom-config-map>` during install or `kubectl edit clusterpolicy` and provide name of custom mig-parted config. Please make sure to change `mig.strategy=mixed` if you have some GPU's with MIG enabled and some not.

**Comment by kpouget** [comment]
Hello, just FYI, I validated that this works as [expected](https://docs.nvidia.com/datacenter/cloud-native/openshift/mig-ocp.html#creating-and-applying-a-custom-mig-configuration) in the v1.9.0-beta with the following ConfigMap:
(mind that the namespace must be `gpu-operator-resources` in v1.8)
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: custom-mig-config
  namespace: nvidia-gpu-operator
data:
  config.yaml: |
    version: v1
    mig-configs:
      all-4g.20gb:
        - devices: all
          mig-enabled: true
          mig-devices:
            "4g.20gb": 1
```
and in the ClusterPolicy:
```
  spec:
    migManager:
      config:
        name: custom-mig-config
```

**Comment by MeranaTona** [comment]
So I followed the suggested custom MIG config part: https://docs.nvidia.com/datacenter/cloud-native/openshift/mig- ocp.html#creating-and-applying-a-custom-mig-configuration and used this yaml as guidance: https://gitlab.com/nvidia/kubernetes/gpu-operator/-/blob/v1.8.2/assets/state-mig-manager/0400_configmap.yaml . So custom config map is present and referenced in clusterpolicy.

After labeling the node:
`kubectl label nodes my_node nvidia.com/mig.config=all-2g.10gb`

Result "failed"
```
kubectl describe node my_node | grep -i mig.config
                    nvidia.com/mig.config=all-2g.10gb
                    nvidia.com/mig.config.state=failed
```

Going into mig-manager-pod:
`kubectl exec -it nvidia-mig-manager-4k5w4 -n gpu-operator-resources -- /bin/bash`
Then:
`cat /mig-parted-config/config.yaml`
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: custom-mig-config
  namespace: gpu-operator-resources
data:
  config.yaml: |
    version: v1
    mig-configs:
      all-disabled:
        - devices: all
          mig-enabled: false

      # A100-40GB
      all-1g.5gb:
        - devices: all
          mig-enabled: true
          mig-devices:
            "1g.5gb": 7

      all-2g.10gb:
        - devices: all
          mig-enabled: true
          mig-devices:
            "2g.10gb": 3

      all-3g.20gb:
        - devices: all
          mig-enabled: true
          mig-devices:
            "3g.20gb": 2

      all-7g.40gb:
        - devices: all
          mig-enabled: true
          mig-devices:
            "7g.40gb": 1

      a100-4x1g.5gb-1x3g.20gb:
        - devices: all
          mig-enabled: true
          mig-devices:
            "1g.4gb": 4
            "3g.20gb": 1

      # A100-80GB
      all-1g.10gb:
        - devices: all
          mig-enabled: true
          mig-devices:
            "1g.10gb": 7

      all-2g.20gb:
        - devices: all
          mig-enabled: true
          mig-devices:
            "2g.20gb": 3

      all-3g.40gb:
        - devices: all
          mig-enabled: true
          mig-devices:
            "3g.40gb": 2

      all-7g.80gb:
        - devices: all
          mig-enabled: true
          mig-devices:
            "7g.80gb": 1

      # A30-24GB
      all-1g.6gb:
        - devices: all
          mig-enabled: true
          mig-devices:
            "1g.6gb": 4

      all-2g.12gb:
        - devices: all
          mig-enabled: true
          mig-devices:
            "2g.12gb": 2

      all-4g.24gb:
        - devices: all
          mig-enabled: true
          mig-devices:
            "4g.24gb": 1

      # PG506-96GB
      all-1g.12gb:
        - devices: all
          mig-enabled: true
          mig-devices:
            "1g.12gb": 7

      all-2g.24gb:
        - devices: all
          mig-enabled: true
          mig-devices:
            "2g.24gb": 3

      all-3g.48gb:
        - devices: all
          mig-enabled: true
          mig-devices:
            "3g.48gb": 2

      all-7g.96gb:
        - devices: all
          mig-enabled: true
          mig-devices:
            "7g.96gb": 1

      # A100-40GB, A100-80GB, A30-24GB, PG506-96GB
      all-balanced:
        # A100-40GB
        - device-filter: ["0x20B010DE", "0x20B110DE", "0x20F110DE"]
          devices: all
          mig-enabled: true
          mig-devices:
            "1g.5gb": 2
            "2g.10gb": 1
            "3g.20gb": 1

        # A100-80GB
        - device-filter: ["0x20B210DE", "0x20B510DE"]
          devices: all
          mig-enabled: true
          mig-devices:
            "1g.10gb": 2
            "2g.20gb": 1
            "3g.40gb": 1

        # A30-24GB
        - device-filter: "0x20B710DE"
          devices: all
          mig-enabled: true
          mig-devices:
            "1g.6gb": 2
            "2g.12gb": 1

        # PG506-96GB
        - device-filter: "0x20B610DE"
          devices: all
          mig-enabled: true
          mig-devices:
            "1g.12gb": 2
            "2g.24gb": 1
            "3g.48gb": 1

```
And:
`nvidia-mig-parted -d assert --valid-config -f /mig-parted-config/config.yaml`
```
DEBU[0000] Parsing config file...
FATA[0000] Error parsing config file: unmarshal error: error unmarshaling JSON: while decoding JSON: unable to parse with missing 'version' field

```
But version is set...

**Comment by kpouget** [comment]
if you see this
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: custom-mig-config
  namespace: gpu-operator-resources
data:
  config.yaml: |
    version: v1
    mig-configs:
      all-disabled:
...
```
in ` cat /mig-parted-config/config.yaml` you indeed have an issue! `mig-parted` expects only the `config.yaml` bits, starting with
```
version: v1
mig-configs:
  all-disabled:
...
```
or it's a copy-and-paste mistake?

**Comment by MeranaTona** [comment]
You are right! It's working now.
```
 kubectl describe node my_node | grep -i mig.config
                    nvidia.com/mig.config=a100-4x1g.5gb-1x3g.20gb
                    nvidia.com/mig.config.state=success
```

 Thank you both for the support.

For documentation my custom-mig-config.yaml:
```
version: v1
mig-configs:
  all-disabled:
    - devices: all
      mig-enabled: false

  all-enabled:
    - devices: all
      mig-enabled: true
      mig-devices: {}

  all-1g.5gb:
    - devices: all
      mig-enabled: true
      mig-devices:
        "1g.5gb": 7

  all-2g.10gb:
    - devices: all
      mig-enabled: true
      mig-devices:
        "2g.10gb": 3

  all-3g.20gb:
    - devices: all
      mig-enabled: true
      mig-devices:
        "3g.20gb": 2

  all-balanced:
    - devices: all
      mig-enabled: true
      mig-devices:
        "1g.5gb": 2
        "2g.10gb": 1
        "3g.20gb": 1

  a100-4x1g.5gb-1x3g.20gb:
    - devices: all
      mig-enabled: true
      mig-devices:
        "1g.5gb": 4
        "3g.20gb": 1

  custom-config:
    - devices: [0,1,2,3]
      mig-enabled: false
    - devices: [4]
      mig-enabled: true
      mig-devices:
        "1g.5gb": 7
    - devices: [5]
      mig-enabled: true
      mig-devices:
     
```
