### ISSUE TITLE
Containers with 0 or no GPU assignment should not be able to see GPUs

### ISSUE THREAD

**Issue by sjdrc** [NVIDIA/gpu-operator#284]
_The template below is mostly useful for bug reports and support questions. Feel free to remove anything which doesn't apply to you and add more information where it makes sense._

### 1. Quick Debug Checklist
- [X] Are you running on an Ubuntu 18.04 node?
- [X] Are you running Kubernetes v1.13+? 1.22.3+k3s1
- [X] Are you running Docker (>= 18.06) or CRIO (>= 1.13+)? docker 19.03.15
- [X] Do you have `i2c_core` and `ipmi_msghandler` loaded on the nodes? ipmi_msghandler and generic kernel
- [X] Did you apply the CRD (`kubectl describe clusterpolicies --all-namespaces`)

### 1. Issue or feature description
I want to prevent containers from using GPU resources by default.

I have 7 GPUs attached to my host. When requesting `nvidia.com/gpu:` with a number between 1 and 7, then the correct number of GPUs are visible to the container. However, when specifying `nvidia.com/gpu: 0` or omitting the resource request altogether, all GPUs are visible to the container.

https://github.com/NVIDIA/k8s-device-plugin/issues/61
This issue seems to be describing my problem (specifically regarding specifying 0 GPUs, not omitting the request). And there is a comment suggesting to change the container toolkit settings. However, this is not deployed on my host as I am deploying the nvidia-container-toolkit with gpu-operator.

### 2. Steps to reproduce the issue
```
apiVersion: v1
kind: Pod
metadata:
  name: cuda-test
spec:
  restartPolicy: OnFailure
  containers:
  - name: busybox
    image: "busybox"
    command: ["true"]
  initContainers:
  - name: 0-gpu
    image: "nvidia/cuda:11.3.1-base"
    command: ["nvidia-smi"]
    resources:
      limits:
         nvidia.com/gpu: 0
  - name: 1-gpu
    image: "nvidia/cuda:11.3.1-base"
    command: ["nvidia-smi"]
    resources:
      limits:
         nvidia.com/gpu: 1
  - name: 2-gpu
    image: "nvidia/cuda:11.3.1-base"
    command: ["nvidia-smi"]
    resources:
      limits:
         nvidia.com/gpu: 2
  - name: no-gpu
    image: "nvidia/cuda:11.3.1-base"
    command: ["nvidia-smi"]
```
