### ISSUE TITLE
GPU operator is uncordoning cordonned/drained nodes

### ISSUE THREAD

**Issue by klamkma** [NVIDIA/gpu-operator#304]
### 1. Issue or feature description
We are using:

Helm Chart:
gpu-operator v1.8.2

In values we set:
```
  driver:
    manager:
      env:
        - name: ENABLE_AUTO_DRAIN
          value: "false"
        - name: DRAIN_USE_FORCE
          value: "false"
        - name: DRAIN_POD_SELECTOR_LABEL
          value: "gpu=drain"
        - name: DRAIN_TIMEOUT_SECONDS
          value: "0s"
        - name: DRAIN_DELETE_EMPTYDIR_DATA
          value: "false"
```

Logs of init container k8s-driver-manager:
```
nvidia driver module is already loaded with refcount 350
Shutting down all GPU clients on the current node by disabling their component-specific nodeSelector labels
node/xxx labeled
Waiting for the operator-validator to shutdown
pod/nvidia-operator-validator-jz2q9 condition met
Waiting for the container-toolkit to shutdown
pod/nvidia-container-toolkit-daemonset-znwjf condition met
Waiting for the device-plugin to shutdown
Waiting for gpu-feature-discovery to shutdown
pod/gpu-feature-discovery-96qmg condition met
Waiting for dcgm-exporter to shutdown
Unloading NVIDIA driver kernel modules...
nvidia_modeset       1228800  0
nvidia_uvm           1146880  4
nvidia              34086912  350 nvidia_uvm,nvidia_modeset
Could not unload NVIDIA driver kernel modules, driver is in use
Auto drain of the node xxx is disabled
Failed to uninstall nvidia driver components
Uncordoning node xxx...
node/xxx already uncordoned
Rescheduling all GPU clients on the current node by enabling their component-specific nodeSelector labels
node/xxx labeled
```

As you can see in the logs, init container will uncordon node, even if we cordoned that node manually on purpose.

### 2. Steps to reproduce the issue

1. Drain kubernetes node,
2. Restart nvidia-driver-daemonset pod which is running on the drained node,
3. Check nodes status. The node which was drained is not cordoned anymore.

How to disable this feature? For maintenance we need sometimes to drain nodes and we cannot have nvidia operator uncordoning them automatically.
Thank you.
