### ISSUE TITLE
Daemonsets fail to start up when using psp.enabled

### ISSUE THREAD

**Issue by mac-chaffee** [NVIDIA/gpu-operator#314]
### 1. Issue or feature description

If gpu-operator is deployed to a cluster using PodSecurityPolicies like the one that comes with [kubespray](https://github.com/kubernetes-sigs/kubespray/blob/daed3e5b6a085ac99e076b51d314fcf76e4127b4/roles/kubernetes-apps/cluster_roles/defaults/main.yml#L3), hostPath volumes aren't allowed.

Since the `node-feature-discovery-worker` daemonset requires hostPath volumes, it won't be able to start up, even with `psp.enabled=true` because there are no Roles/ClusterRoles that allow the default serviceaccount to `use` any specific PSPs.

### 2. Steps to reproduce the issue

1. Deploy a default podsecuritypolicy which disallows hostPath volumes
2. `helm upgrade --install gpu-operator -n gpu-operator nvidia/gpu-operator --version v1.9.1 --set toolkit.version=1.7.2-centos8 --set psp.enabled=true`
3. Observe the daemonset is unable to spawn pods, and the events show the hostPath volumes are being blocked.

I think to fix the issue, the default serviceaccount in the namespace (which is used to spawn pods from a daemonset) needs to have a Role/Rolebinding which allows it to use the `gpu-operator-restricted` PSP:

```
 apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    app.kubernetes.io/name: node-feature-discovery
  name: gpu-operator-ds-psp
  namespace: gpu-operator
rules:
- apiGroups:
  - policy
  resourceNames:
  - gpu-operator-restricted
  resources:
  - podsecuritypolicies
  verbs:
  - use
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app.kubernetes.io/name: node-feature-discovery
  name: gpu-operator-ds-psp
  namespace: gpu-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: gpu-operator-ds-psp
# This subject allows the daemonset (using default serviceaccount) to use the PSP which allows hostPath mounts
subjects:
- kind: ServiceAccount
  name: default
  namespace: gpu-operator
```

**Comment by myllyja** [comment]
I also ran into this issue in a cluster where PodSecurityPolicy denies the use of hostPath volumes, the error shown when looking at `kubectl describe --namespace gpu-operator daemonset.apps/nvidia-gpu-operator-node-feature-discovery-worker` is 


`
Error creating: pods "nvidia-gpu-operator-node-feature-discovery-worker-" is forbidden: PodSecurityPolicy: unable to admit pod: [spec.volumes[0]: Invalid value: "hostPath": hostPath volumes are not allowed to be used...
`

Looking at how the psp.enabled was implemented in [Enable auto creation of PodSecurityPolicies to apply to all operator Pods.
](https://github.com/NVIDIA/gpu-operator/commit/c91af8cab8c69744972cb9e2ea623f3e334762e6) it looks like the service account node-feature-discovery was added, but it's not used in the nvidia-gpu-operator-node-feature-discovery-worker daemonset spec.

As a workaround I added the ServiceAccountName into the daemonset by editing it manually.
`kubectl edit --namespace gpu-operator daemonset.apps/nvidia-gpu-operator-node-feature-discovery-worker`
And then under the spec.template.spec part I added a line for the serviceaccountname next to the securitycontext
```
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccountName: node-feature-discovery    <-- this line was added
      terminationGracePeriodSeconds: 30
      tolerations:
```

After this edit, the nvidia-gpu-operator-node-feature-discovery-worker-* pods started successfully. Maybe the setting was simply forgotten from the https://github.com/NVIDIA/gpu-operator/blob/master/deployments/gpu-operator/charts/node-feature-discovery/templates/worker.yaml spec?
