### ISSUE TITLE
[feature] Dynamic MIG partitioner

### ISSUE THREAD

**Issue by elgalu** [NVIDIA/gpu-operator#361]
Would it be possible that the gpu operator makes the MIG setup transparent such that the end user can directly request per-pod GPU memory requirements on-demand while, under the hood, MIG configuration is dynamically re-partitioned? i.e. without any intervention of a sysadmin / devops team.

```yaml
# requesting eight 40Gi MIG slices
resources:
    limits:
        nvidia.com/gpu: 8
        nvidia.com/gpu_memory: "40Gi"
```

https://www.nvidia.com/en-us/technologies/multi-instance-gpu/
> MIG instances can also be dynamically reconfigured
