### ISSUE TITLE
Docs error in Getting Started

### ISSUE THREAD

**Issue by chengleqi** [NVIDIA/gpu-operator#374]
In the [Custom configuration for runtime containerd](https://docs.nvidia.com/datacenter/cloud-native/gpu-operator/getting-started.html#custom-configuration-for-runtime-containerd) Section. The yaml provided:
![选区_021](https://user-images.githubusercontent.com/53958238/180204491-c939721e-8d29-404d-9e23-4bb4b5befdac.png)

But it should be like this:
```yaml
toolkit:
  env:
    - name: CONTAINERD_CONFIG
      value: /var/lib/rancher/k3s/agent/etc/containerd/config.toml
    - name: CONTAINERD_SOCKET
      value: /run/k3s/containerd/containerd.sock
    - name: CONTAINERD_RUNTIME_CLASS
      value: nvidia
    - name: CONTAINERD_SET_AS_DEFAULT
      value: "true"
```

this is my k3s config.
