### ISSUE TITLE
CUDA validators crashlooping while other cuda containers run fine

### ISSUE THREAD

**Issue by faiq** [NVIDIA/gpu-operator#389]
_The template below is mostly useful for bug reports and support questions. Feel free to remove anything which doesn't apply to you and add more information where it makes sense._

### 1. Quick Debug Checklist
- [ ] Are you running on an Ubuntu 18.04 node?
- [x] Are you running Kubernetes v1.13+?
- [ ] Are you running Docker (>= 18.06) or CRIO (>= 1.13+)?
- [ ] Do you have `i2c_core` and `ipmi_msghandler` loaded on the nodes?
- [ ] Did you apply the CRD (`kubectl describe clusterpolicies --all-namespaces`)

### 1. Issue or feature description:

The cuda validators in my cluster are in `Init:CrashLoopBackOff `while other cuda vector addition workloads run completely fine. 

```sh 
$ kubectl get po 
NAME                                       READY   STATUS                  RESTARTS        AGE
gpu-feature-discovery-cqjqx                1/1     Running                 0               28m
gpu-feature-discovery-x4qh2                1/1     Running                 0               28m
gpu-operator-77787587cf-cxnzl              1/1     Running                 0               28m
nvidia-container-toolkit-daemonset-bk28j   1/1     Running                 0               28m
nvidia-container-toolkit-daemonset-qvftc   1/1     Running                 0               28m
nvidia-cuda-validator-ccn65                0/1     Init:CrashLoopBackOff   5 (23s ago)     3m29s
nvidia-cuda-validator-p7sgd                0/1     Init:CrashLoopBackOff   5 (16s ago)     3m18s
nvidia-dcgm-exporter-p5wrc                 1/1     Running                 0               28m
nvidia-dcgm-exporter-rvnz6                 1/1     Running                 0               28m
nvidia-device-plugin-daemonset-2bfmt       1/1     Running                 0               28m
nvidia-device-plugin-daemonset-pvphw       1/1     Running                 0               28m
nvidia-operator-validator-5qfx2            0/1     Init:2/4                5 (4m55s ago)   28m
nvidia-operator-validator-nc9n6            0/1     Init:2/4                5 (4m40s ago)   28m
```

On closer inspection its the vector add that's giving us an issue when getting the logs we get

```
$ kubectl logs nvidia-cuda-validator-ccn65 -c cuda-validation --previous 
Failed to allocate device vector A (error code all CUDA-capable devices are busy or unavailable)!
[Vector addition of 50000 elements]
``` 
However, I am able to deploy other cudavector workloads for example 

```
$ kubectl get po -n e2e-gpu-workload 
NAME                READY   STATUS             RESTARTS         AGE
cuda-vector-add     0/1     Completed          0                29m
cuda-vector-add-2   0/1     CrashLoopBackOff   10 (2m19s ago)   14m
cuda-vector-add-3   0/1     CrashLoopBackOff   6 (4m19s ago)    11m
cuda-vector-add-4   0/1     Completed          0                9m34s
```

and another look, printing out the container images for the running and non-running pods 

```
$ kubectl get po -n e2e-gpu-workload -o custom-columns=CONTAINER:.spec.containers[0].name,IMAGE:.spec.containers[0].image
CONTAINER        IMAGE
cuda-vectoradd   nvidia/samples:vectoradd-cuda11.2.1
cuda-vectoradd   nvcr.io/nvidia/cloud-native/gpu-operator-validator:v1.11.1
cuda-vectoradd   docker.io/anjia0532/cuda-vector-add:v0.1
cuda-vectoradd   docker.io/anjia0532/cuda-vector-add:v0.1
```
when we look at the logs we find that everything works fine 

```
$ kubectl logs -n e2e-gpu-workload cuda-vector-add
[Vector addition of 50000 elements]
Copy input data from the host memory to the CUDA device
CUDA kernel launch with 196 blocks of 256 threads
Copy output data from the CUDA device to the host memory
Test PASSED
Done
``` 
and expanding the pod definition we get 

```yaml 
$ kubectl get po -n e2e-gpu-workload cuda-vector-add -o yaml
apiVersion: v1
kind: Pod
metadata:
  annotations:
    cni.projectcalico.org/containerID: 9cbccd5849cd9f8a0b1670b84392deacfac4a55eaa05541ef83ab66df24de089
    cni.projectcalico.org/podIP: ""
    cni.projectcalico.org/podIPs: ""
  creationTimestamp: "2022-08-10T22:59:38Z"
  name: cuda-vector-add
  namespace: e2e-gpu-workload
  resourceVersion: "16028"
  uid: 17064311-b8a5-4ff3-bd4c-c3a9665d2ec4
spec:
  containers:
  - image: nvidia/samples:vectoradd-cuda11.2.1
    imagePullPolicy: IfNotPresent
    name: cuda-vectoradd
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-d7zbx
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeSelector:
    nvidia.com/gpu.count: "1"
```

### 2. Steps to reproduce the issue

I installed the operator with the following command:

```
helm install --wait --generate-name  --set nfd.enabled=false --set driver.enabled=false --set toolkit.version=1.6.0-centos7  nvidia/gpu-operator
``` 

In my setup I installed the nvidia device drivers and cuda drivers on the host using the runfile and am using the operator to install the container runtime. 

### 3. Information to [attach](https://help.github.com/articles/file-attachments-on-issues-and-pull-requests/) (optional if deemed irrelevant)

 - [ ] kubernetes pods status: `kubectl get pods --all-namespaces`
 - [ ] kubernetes daemonset status: `kubectl get ds --all-namespaces`
 - [ ] If a pod/ds is in an error state or pending state `kubectl describe pod -n NAMESPACE POD_NAME`
 - [ ] If a pod/ds is in an error state or pending state `kubectl logs -n NAMESPACE POD_NAME`

 - [ ] Output of running a container on the GPU machine: `docker run -it alpine echo foo`
 - [ ] Docker configuration file: `cat /etc/docker/daemon.json`
 - [ ] Docker runtime configuration: `docker info | grep runtime`

 - [ ] NVIDIA shared directory: `ls -la /run/nvidia`
 - [x] NVIDIA packages directory: `ls -la /usr/local/nvidia/toolkit`
 - [ ] NVIDIA driver directory: `ls -la /run/nvidia/driver`
 - [ ] kubelet logs `journalctl -u kubelet > kubelet.logs`

When I run nvidia-smi on the host i get the following, indicating that cuda is installed alright.

```
[root@ip-10-0-101-7 bin]# nvidia-smi
Wed Aug 10 23:40:28 2022
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 470.82.01    Driver Version: 470.82.01    CUDA Version: 11.4     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla K80           Off  | 00000000:00:1E.0 Off |                    0 |
| N/A   35C    P8    30W / 149W |      0MiB / 11441MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+
```

as well as running  a container with cuda 

```
[root@ip-10-0-101-7 bin]# ctr run --rm --gpus 0 -t docker.io/nvidia/samples:vectoradd-cuda11.2.1 add2
[Vector addition of 50000 elements]
Copy input data from the host memory to the CUDA device
CUDA kernel launch with 196 blocks of 256 threads
Copy output data from the CUDA device to the host memory
Test PASSED
Done
```

```
[root@ip-10-0-101-7 bin]# ls -la /usr/local/nvidia/toolkit
total 8548
drwxr-xr-x. 3 root root    4096 Aug 10 23:04 .
drwxr-xr-x. 3 root root      21 Aug 10 23:04 ..
drwxr-xr-x. 3 root root      38 Aug 10 23:04 .config
lrwxrwxrwx. 1 root root      28 Aug 10 23:04 libnvidia-container.so.1 -> libnvidia-container.so.1.4.0
-rwxr-xr-x. 1 root root  179192 Aug 10 23:04 libnvidia-container.so.1.4.0
-rwxr-xr-x. 1 root root     154 Aug 10 23:04 nvidia-container-cli
-rwxr-xr-x. 1 root root   43024 Aug 10 23:04 nvidia-container-cli.real
-rwxr-xr-x. 1 root root     342 Aug 10 23:04 nvidia-container-runtime
-rwxr-xr-x. 1 root root     350 Aug 10 23:04 nvidia-container-runtime-experimental
-rwxr-xr-x. 1 root root 3991000 Aug 10 23:04 nvidia-container-runtime.experimental
lrwxrwxrwx. 1 root root      24 Aug 10 23:04 nvidia-container-runtime-hook -> nvidia-container-toolkit
-rwxr-xr-x. 1 root root 2359384 Aug 10 23:04 nvidia-container-runtime.real
-rwxr-xr-x. 1 root root     198 Aug 10 23:04 nvidia-container-toolkit
-rwxr-xr-x. 1 root root 2147896 Aug 10 23:04 nvidia-container-toolkit.real
[root@ip-10-0-101-7 bin]#
```

Any guidance would be greatly appreciated, and please let me know how I can help. 

Thank you.

**Comment by shivamerla** [comment]
@faiq I see that container-toolkit version is very old (1.4.0) where Operator v1.11.1 deploys toolkit version 1.10.0. Wondering if this is causing the issue as vectorAdd sample we use is latest one based on CUDA 11.7. Can you update the container toolkit to more latest one?

**Comment by faiq** [comment]
I can absolutely give that a try with the adjusted value.

In a related topic, would you be interested in a contribution to infer the toolkit os in a similar way as the operator does for driver does for driver. As there seems to be OS specific library dependencies see: https://github.com/NVIDIA/gpu-operator/issues/72#issuecomment-742023528

IMO this would greatly improve the UX of the operator.

**Comment by shivamerla** [comment]
@faiq yes, that was the plan initially but we couldn't do that as toolkit  images were not available for all variants. Also, toolkit image with OS variant `ubuntu18.04` works across `ubuntu20.04` and `ubuntu22.04`. Also, once the fix suggested by Kevin in the linked thread is complete, we don't need different variants at all for each version of a given OS.

**Comment by BHSDuncan** [comment]
I'm having a very similar issue when installing the Cloud Native Core (6.2) stack via one of the available Ansible playbooks. However, my container toolkit is 1.10.0. Yet I still get the same error message as OP.

I can give the rest of the versions of whatever is needed here, but I wanted to check if it's ok to do so here, or if I should start a new issue (and if so, should it be here or in the CNC repository)?

Thank you.

**Comment by faiq** [comment]
@shivamerla I've tried again with a newer version of the container toolkit - v1.10.0-centos-7 and still no luck 

```yaml 
$ kubectl describe po nvidia-container-toolkit-daemonset-hb5z6
Name:                 nvidia-container-toolkit-daemonset-hb5z6
Namespace:            default
Priority:             2000001000
Priority Class Name:  system-node-critical
Node:                 ip-10-0-115-55.us-west-2.compute.internal/10.0.115.55
Start Time:           Fri, 12 Aug 2022 09:33:01 -0700
Labels:               app=nvidia-container-toolkit-daemonset
                      controller-revision-hash=bd5d94876
                      pod-template-generation=2
Annotations:          cni.projectcalico.org/containerID: 54adee8127a6836a1ce81df53b3a8d9c8bcd7c4f61d696c4b7b5f36263221ca3
                      cni.projectcalico.org/podIP: 192.168.114.134/32
                      cni.projectcalico.org/podIPs: 192.168.114.134/32
Status:               Running
IP:                   192.168.114.134
IPs:
  IP:           192.168.114.134
Controlled By:  DaemonSet/nvidia-container-toolkit-daemonset
Init Containers:
  driver-validation:
    Container ID:  containerd://179a13f5197da79feac867a2498529f102e12f92d283f273ae430581b6d8e81c
    Image:         nvcr.io/nvidia/cloud-native/gpu-operator-validator:v1.11.0
    Image ID:      nvcr.io/nvidia/cloud-native/gpu-operator-validator@sha256:d83aee1c7a9c3aa39e3947f0bd206e7955390943b8e3f2e56bdb96bc4ef99d69
    Port:          <none>
    Host Port:     <none>
    Command:
      sh
      -c
    Args:
      nvidia-validator
    State:          Terminated
      Reason:       Completed
      Exit Code:    0
      Started:      Fri, 12 Aug 2022 09:33:02 -0700
      Finished:     Fri, 12 Aug 2022 09:33:04 -0700
    Ready:          True
    Restart Count:  0
    Environment:
      WITH_WAIT:  true
      COMPONENT:  driver
    Mounts:
      /host from host-root (ro)
      /run/nvidia/driver from driver-install-path (rw)
      /run/nvidia/validations from run-nvidia-validations (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-njrtz (ro)
Containers:
  nvidia-container-toolkit-ctr:
    Container ID:  containerd://05d50be00b768266ce5f603505e9cae580888ca4a1fbeb076835e80b94b649d7
    Image:         nvcr.io/nvidia/k8s/container-toolkit:v1.10.0-centos7
    Image ID:      nvcr.io/nvidia/k8s/container-toolkit@sha256:80c05e1db6462d6561cfa46d9d0c58bb0e9c222df8bcada56182b3a58c48072c
    Port:          <none>
    Host Port:     <none>
    Command:
      bash
      -c
    Args:
      [[ -f /run/nvidia/validations/host-driver-ready ]] && driver_root=/ || driver_root=/run/nvidia/driver; export NVIDIA_DRIVER_ROOT=$driver_root; exec nvidia-toolkit /usr/local/nvidia
    State:          Running
      Started:      Fri, 12 Aug 2022 09:33:37 -0700
    Ready:          True
    Restart Count:  0
    Environment:
      RUNTIME_ARGS:              --socket /runtime/sock-dir/containerd.sock --config /runtime/config-dir/config.toml
      RUNTIME:                   containerd
      CONTAINERD_RUNTIME_CLASS:  nvidia
    Mounts:
      /host from host-root (ro)
      /run/nvidia from nvidia-run-path (rw)
      /runtime/config-dir/ from containerd-config (rw)
      /runtime/sock-dir/ from containerd-socket (rw)
      /usr/local/nvidia from nvidia-local (rw)
      /usr/share/containers/oci/hooks.d from crio-hooks (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-njrtz (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             True 
  ContainersReady   True 
  PodScheduled      True 
Volumes:
  nvidia-run-path:
    Type:          HostPath (bare host directory volume)
    Path:          /run/nvidia
    HostPathType:  DirectoryOrCreate
  run-nvidia-validations:
    Type:          HostPath (bare host directory volume)
    Path:          /run/nvidia/validations
    HostPathType:  DirectoryOrCreate
  driver-install-path:
    Type:          HostPath (bare host directory volume)
    Path:          /run/nvidia/driver
    HostPathType:  
  host-root:
    Type:          HostPath (bare host directory volume)
    Path:          /
    HostPathType:  
  nvidia-local:
    Type:          HostPath (bare host directory volume)
    Path:          /usr/local/nvidia
    HostPathType:  
  crio-hooks:
    Type:          HostPath (bare host directory volume)
    Path:          /run/containers/oci/hooks.d
    HostPathType:  
  containerd-config:
    Type:          HostPath (bare host directory volume)
    Path:          /etc/containerd
    HostPathType:  
  containerd-socket:
    Type:          HostPath (bare host directory volume)
    Path:          /run/containerd
    HostPathType:  
  kube-api-access-njrtz:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  3607
    ConfigMapName:           kube-root-ca.crt
    ConfigMapOptional:       <nil>
    DownwardAPI:             true
QoS Class:                   BestEffort
Node-Selectors:              nvidia.com/gpu.deploy.container-toolkit=true
Tolerations:                 node.kubernetes.io/disk-pressure:NoSchedule op=Exists
                             node.kubernetes.io/memory-pressure:NoSchedule op=Exists
                             node.kubernetes.io/not-ready:NoExecute op=Exists
                             node.kubernetes.io/pid-pressure:NoSchedule op=Exists
                             node.kubernetes.io/unreachable:NoExecute op=Exists
                             node.kubernetes.io/unschedulable:NoSchedule op=Exists
                             nvidia.com/gpu:NoSchedule op=Exists
Events:
```

Failing pod 

```
nvidia-cuda-validator-dgmwl                0/1     Init:CrashLoopBackOff   2 (12s ago)   30s
```

failing pod logs 

```
$ kubectl logs nvidia-cuda-validator-dgmwl --previous -c cuda-validation
[Vector addition of 50000 elements]
Failed to allocate device vector A (error code all CUDA-capable devices are busy or unavailable)!
``` 

Completed pod + image

```
 kubectl get po cuda-vector-add -o yaml | grep image
      {"apiVersion":"v1","kind":"Pod","metadata":{"annotations":{},"name":"cuda-vector-add","namespace":"default"},"spec":{"containers":[{"image":"nvidia/samples:vectoradd-cuda11.2.1","name":"cuda-vectoradd"}],"nodeSelector":{"nvidia.com/gpu.count":"1"},"restartPolicy":"OnFailure"}}
  - image: nvidia/samples:vectoradd-cuda11.2.1
    imagePullPolicy: IfNotPresent
    image: docker.io/nvidia/samples:vectoradd-cuda11.2.1
``` 

I'll try with this new RC cut and see if it resolves the issue, but it seems like its a problem with the test itself - v1.11.0-rc.2-centos7
