### ISSUE TITLE
nvidia-device-plugin-validator fails after node reboot (with MIG enabled)

### ISSUE THREAD

**Issue by dasantonym** [NVIDIA/gpu-operator#403]
# System

Running on bare-metal

- Ubuntu 20.04.4
- Kubernetes v1.24.3
- Containerd 1.6.7
- GPU-Operator v1.11.1

# Setup

GPU-Operator is installed with:

```
helm install --wait --debug --generate-name --create-namespace \
      nvidia/gpu-operator \
      -n gpu-operator \
      --set migManager.config.name=mig-config \
      --set mig.strategy=mixed \
      --set driver.enabled=false \
      --set toolkit.enabled=false
```

MIG-Config:

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: mig-config
  namespace: gpu-operator
data:
  config.yaml: |
    version: v1
    mig-configs:
      all-disabled:
        - devices: all
          mig-enabled: false
      node-standard:
        - devices: [0]
          mig-enabled: true
          mig-devices:
            "2g.20gb": 3
        - devices: [1]
          mig-enabled: true
          mig-devices:
            "2g.20gb": 3
        - devices: [2]
          mig-enabled: true
          mig-devices:
            "3g.40gb": 2
        - devices: [3]
          mig-enabled: true
          mig-devices:
            "3g.40gb": 2
        - devices: [4,5,6,7]
          mig-enabled: false
```

# Issue

I am running a cluster with multiple GPU-Nodes and some of the nodes are using MIG, others are not. Now, as long as all nodes have their MIG config set to `all-disabled`, everything is fine. As soon as I set one node to a mixed MIG config, the `nvidia-device-plugin-validator` fails with the message:

```
spec: failed to generate spec: lstat /run/nvidia/driver/dev/nvidiactl: no such file or directory
```

Once I switch back the MIG config to `all-disabled`, the validation succeeds again.

**Edit:** To further clarify: The validator only fails with the wrong driver root value for the node where I activate MIG. The other validator pods are unaffected, even after further (node) restarts, as long as MIG remains off.

**Comment by shivamerla** [comment]
@dasantonym to confirm, wrong driver root was set on the node nvidia-container-runtime config file? Or did you see wrong NVIDIA_DRIVER_ROOT set within the device-plugin pod?

**Comment by dasantonym** [comment]
Thanks for the prompt reply. I did not make any config changes, but where should I look for the nvidia-container-runtime file? Do you mean the containerd config file or is this also located in a specific pod?

The host's containerd config looks like this:

```toml
version = 2
[plugins]
  [plugins."io.containerd.grpc.v1.cri"]
    [plugins."io.containerd.grpc.v1.cri".containerd]
      default_runtime_name = "nvidia"

      [plugins."io.containerd.grpc.v1.cri".containerd.runtimes]
        [plugins."io.containerd.grpc.v1.cri".containerd.runtimes.runc]
          [plugins."io.containerd.grpc.v1.cri".containerd.runtimes.runc.options]
            SystemdCgroup = true
        [plugins."io.containerd.grpc.v1.cri".containerd.runtimes.nvidia]
          privileged_without_host_devices = false
          runtime_engine = ""
          runtime_root = ""
          runtime_type = "io.containerd.runc.v2"
          [plugins."io.containerd.grpc.v1.cri".containerd.runtimes.nvidia.options]
            BinaryName = "/usr/bin/nvidia-container-runtime"
```

The env var NVIDIA_DRIVER_ROOT is set to `/` for the failing pod.
