### ISSUE TITLE
gpu-operator failing on rke2

### ISSUE THREAD

**Issue by sasajl** [NVIDIA/gpu-operator#406]
I have a cluster running rke2 v1.22 with a worker node running Ubuntu 20.04 that has a Tesla-T4.

The gpu-operator fails with a message: 
time="2022-09-19T11:52:23Z" level=warning msg="Error signaling containerd, attempt 5/6: unable to dial: dial unix /runtime/sock-dir/containerd.sock: connect: no such file or directory"

more detailed log attached.

Suggestions welcome and any other suggestions for getting this to work on rke2.

[gpu-operator.txt](https://github.com/NVIDIA/gpu-operator/files/9599958/gpu-operator.txt)

**Comment by cdesiniotis** [comment]
The containerd socket and configuration file are located at custom paths on RKE2. Can you try pointing the NVIDIA Container Toolkit to the proper locations by setting the following env in ClusterPolicy:
```
toolkit:
  env:
    - name: CONTAINERD_CONFIG
      value: /var/lib/rancher/k3s/agent/etc/containerd/config.toml
    - name: CONTAINERD_SOCKET
      value: /run/k3s/containerd/containerd.sock
```
