### ISSUE TITLE
gpu-operator devicePlugin error

### ISSUE THREAD

**Issue by dioguerra** [NVIDIA/gpu-operator#412]
### 1. Issue or feature description
When installing the gpu-operator if I setup a different than default (time-slicing-config) devicePlugin.config.name for the configMap,
The devicePlugin component does not update the configuration. 
This happens even if in the configpolicy the configMap is correctly populated. Also if this configMap is not present the devicePlugin pod seems to halt.

Using configMap name as the default one 'time-slicing-config' seems to load the user defined config map

### 2. Steps to reproduce the issue
values.yaml
```
gpu-operator:
  enabled: true
  operator:
    defaultRuntime: containerd
  driver:
    repository: foo
    image: nvidia-gpu-driver
    version: "470.129.06"
    imagePullPolicy: Always
  devicePlugin:
    config:
      name: nvidia-time-slicing-config    <- notice the different name
      # default: tesla-t4
```
configMap
```
cat templates/gpus/nvidia-time-slicing-config.yaml 
apiVersion: v1
kind: ConfigMap
metadata:
  name: nvidia-time-slicing-config
  namespace: kube-system
data:
  slice-4: |-
    version: v1
    sharing:
      timeSlicing:
        renameByDefault: true
        failRequestsGreaterThanOne: true
        resources:
        - name: nvidia.com/gpu
          replicas: 4
  slice-10: |-
    version: v1
    sharing:
      timeSlicing:
        renameByDefault: true
        failRequestsGreaterThanOne: true
        resources:
        - name: nvidia.com/gpu
          replicas: 10
```

### 3. More info:
```
cat Chart.yaml  | grep gpu -A 5
  - name: gpu-operator
    version: 1.11.0
```
