### ISSUE TITLE
Docker daemon settings in case of using the GPU Operator

### ISSUE THREAD

**Issue by Kaka1127** [NVIDIA/gpu-operator#42]
Hi 

Would you please give us the settings for docker in case of gpu-operatior?
As you know, when installed the nvidia-driver, nvidia-docker2 for GPU worker, the daemon for docker was set as below.

```
docker_daemon_json:
  default-shm-size: 1G
  default-ulimits:
    memlock:
      name: memlock
      hard: -1
      soft: -1
    stack:
      name: stack
      hard: 67108864
      soft: 67108864
  default-runtime: nvidia
  runtimes:
    nvidia:
      path: /usr/bin/nvidia-container-runtime
      runtimeArgs: []
```

Best regards.
kaka
