### ISSUE TITLE
nvidia/gpu-operator exposes all GPUs in Kubefllow

### ISSUE THREAD

**Issue by hoangtnm** [NVIDIA/gpu-operator#421]
_The template below is mostly useful for bug reports and support questions. Feel free to remove anything which doesn't apply to you and add more information where it makes sense._

### 1. Quick Debug Checklist
- [ ] Are you running on an Ubuntu 18.04 node?
- [x] Are you running Kubernetes v1.13+?
- [x] Are you running Docker (>= 18.06) or CRIO (>= 1.13+)?
- [ ] Do you have `i2c_core` and `ipmi_msghandler` loaded on the nodes?
- [ ] Did you apply the CRD (`kubectl describe clusterpolicies --all-namespaces`)

### 1. Issue or feature description

Hi, I'm deploying [Kubeflow Manifests](https://github.com/kubeflow/manifests) with `nvidia/gpu-operator` and doing experiments in Jupyter notebooks. However, even though I don't specify the `Number of GPUs`, which expects no GPUs to be exposed, all GPUs are still exposed in the notebooks. I don't how which causes the problem or any workaround for this one. Do you have any idea?

### 2. Steps to reproduce the issue

```bash
helm install nvidia/gpu-operator \
  --version=v22.9.0 \
  --generate-name \
  --create-namespace \
  --namespace=gpu-operator-resources \
  --set driver.enabled=false
```

<img width="620" alt="screen_shot_2022-10-14_at_14 23 19" src="https://user-images.githubusercontent.com/35718590/196018924-6e47cccf-442a-46e1-923b-ff195bc7e124.png">
<img width="597" alt="screen_shot_2022-10-14_at_14 23 54" src="https://user-images.githubusercontent.com/35718590/196018929-b9e30db9-a169-4848-927e-0d2a75801bb3.png">

**Comment by shivamerla** [comment]
@hoangtnm  This will happen when `NVIDIA_VISIBLE_DEVICES=all` environment variable is set in the image you are using (which is true for most of the cuda images). Please refer to [this](https://docs.google.com/document/d/1uXVF-NWZQXgP1MLb87_kMkQvidpnkNWicdpO2l9g-fw/edit?usp=sharing) document on ways to prevent using this env without `privileged` mode.

**Comment by hoangtnm** [comment]
@shivamerla Thank you for your prompt reply. As I understand your document, these following modifications should be made into `/etc/nvidia-container-runtime/config.toml`:

```
accept-nvidia-visible-devices-envvar-when-unprivileged = true
accept-nvidia-visible-devices-as-volume-mounts = false
```

However, when I read [another document](https://docs.google.com/document/d/1zy0key-EL6JH50MZgwg96RPYxxXXnVUdxLZwGiyqLd8/edit#heading=h.tec6pygavof) on page 3 by @klueska, the modifications should be:

```
accept-nvidia-visible-devices-envvar-when-unprivileged = false
accept-nvidia-visible-devices-as-volume-mounts = true
```

Therefore, which one is the right way for this problem?

**Comment by elezar** [comment]
@hoangtnm the document that was linked by @shivamerla describes the options and their behaviour. If you want to prevent the use of the `NVIDIA_VISIBLE_DEVICES` environment variable in unprivileged containers, you will have to set:
```
accept-nvidia-visible-devices-envvar-when-unprivileged = false
```
If you then want the device plugin to use volume mounts (and *not* the envvar) to specify devices you additionally need to set:
```
accept-nvidia-visible-devices-as-volume-mounts = true
```
And ensure that the device pluging is tarted with the `device-list-strategy=volume-mounts` option set.

**Comment by shivamerla** [comment]
to make this clear, with operator following params needs to be set during helm install.

```
devicePlugin:
  env:
    ...
    - name: DEVICE_LIST_STRATEGY
      value: volume-mounts
toolkit:
  env:
  ...
     - name: ACCEPT_NVIDIA_VISIBLE_DEVICES_ENVVAR_WHEN_UNPRIVILEGED
       value: "false"
```

**Comment by hoangtnm** [comment]
Hi @elezar @shivamerla, thank you for your prompt replies, they helped my a lot :D However, I just want to confirm the steps along with how to apply those params during `gpu-operator` helm install:

```bash
helm repo add nvidia https://nvidia.github.io/gpu-operator \
  && helm repo update \
  && helm install nvidia/gpu-operator \
  --version=v22.9.0 \
  --generate-name \
  --create-namespace \
  --namespace=gpu-operator-resources \
  --set driver.enabled=false \
  --set devicePlugin.env[0].name=DEVICE_LIST_STRATEGY \
  --set devicePlugin.env[0].value="volume-mounts" \
  --set toolkit.env[0].name=ACCEPT_NVIDIA_VISIBLE_DEVICES_ENVVAR_WHEN_UNPRIVILEGED \
  --set toolkit.env[0].value="false" \
  --wait
```

Is this correct or do I miss something to make it work?

**Comment by elezar** [comment]
I think your understanding is correct. Using the toolkit daemonset should configure the toolkit as required. Note that you would also need to set the `ACCEPT_NVIDIA_VISIBLE_DEVICES_AS_VOLUME_MOUNTS="true"` for the toolkit to trigger it to consider volume mounts.

**Comment by Alwinator** [comment]
For me, it solved the issue with the environment variable, however, if I do a small test with volume mounts enabled, it runs into errors:
```yaml
cat << EOF | oc create -f -
apiVersion: v1
kind: Pod
metadata:
  name: cuda-vectoradd
spec:
  restartPolicy: OnFailure
  containers:
  - name: cuda-vectoradd
    image: "dockerregistry-v2.vih.infineon.com/nvidia/samples:vectoradd-cuda11.2.1"
    resources:
      limits:
        nvidia.com/mig-1g.6gb: 1
EOF
pod/cuda-vectoradd created
```

Pod logs:
```
Failed to allocate device vector A (error code CUDA driver version is insufficient for CUDA runtime version)!
[Vector addition of 50000 elements]
```

**Comment by Alwinator** [comment]
@elezar For me, it solved the issue with the environment variable, however, if I do a small test with volume mounts enabled, it runs into errors:
```yaml
cat << EOF | oc create -f -
apiVersion: v1
kind: Pod
metadata:
  name: cuda-vectoradd
spec:
  restartPolicy: OnFailure
  containers:
  - name: cuda-vectoradd
    image: "example.com/nvidia/samples:vectoradd-cuda11.2.1"
    resources:
      limits:
        nvidia.com/mig-1g.6gb: 1
EOF
pod/cuda-vectoradd created
```

Pod logs:
```
Failed to allocate device vector A (error code CUDA driver version is insufficient for CUDA runtime version)!
[Vector addition of 50000 elements]
```

**Comment by elezar** [comment]
@Alwinator could you please confirm your GPU operator version and values that you have applied to your helm deployment?

**Comment by Alwinator** [comment]
OpenShift 4.10.35 with Kubernetes 1.23
OS on nodes: Red Hat Enterprise Linux CoreOS 410.84.202209231843-0
CRI-O 1.23.3-17.rhaos4.10.git016b1ca.el8
GPU Operator version: 22.9.0
Helm version: v3.6.3

**Comment by elezar** [comment]
> OpenShift 4.10.35 with Kubernetes 1.23 OS on nodes: Red Hat Enterprise Linux CoreOS 410.84.202209231843-0 CRI-O 1.23.3-17.rhaos4.10.git016b1ca.el8 GPU Operator version: 22.9.0 Helm version: v3.6.3

Thanks. And the values used to install the operator?

**Comment by Alwinator** [comment]
The Nvidia Operator 22.9.0 is installed in the nvidia-gpu-operator namespace, with update approval automatic and the cluster policy:
```yaml
apiVersion: nvidia.com/v1
kind: ClusterPolicy
metadata:
  name: gpu-cluster-policy
spec:
  vgpuDeviceManager:
    config:
      default: default
    enabled: true
  migManager:
    enabled: true
  operator:
    defaultRuntime: crio
    initContainer: {}
    runtimeClass: nvidia
    use_ocp_driver_toolkit: true
  dcgm:
    enabled: true
  gfd:
    enabled: true
  dcgmExporter:
    config:
      name: nvidia-dcgm-exporter-custom-config
    enabled: true
    serviceMonitor:
      enabled: true
  driver:
    certConfig:
      name: ''
    enabled: true
    kernelModuleConfig:
      name: ''
    licensingConfig:
      configMapName: ''
      nlsEnabled: false
    repoConfig:
      configMapName: ''
    rollingUpdate:
      maxUnavailable: '1'
    virtualTopology:
      config: ''
  devicePlugin:
    config:
      default: ''
      name: ''
    enabled: true
    env:
      - name: DEVICE_LIST_STRATEGY
        value: volume-mounts
  mig:
    strategy: mixed
  sandboxDevicePlugin:
    enabled: true
  validator:
    plugin:
      env:
        - name: WITH_WORKLOAD
          value: 'true'
  nodeStatusExporter:
    enabled: true
  daemonsets: {}
  sandboxWorkloads:
    defaultWorkload: container
    enabled: false
  vgpuManager:
    enabled: false
  vfioManager:
    enabled: true
  toolkit:
    enabled: true
    env:
      - name: ACCEPT_NVIDIA_VISIBLE_DEVICES_ENVVAR_WHEN_UNPRIVILEGED
        value: 'false'
    installDir: /usr/local/nvidia
status:
  namespace: nvidia-gpu-operator
  state: ready
```
