### ISSUE TITLE
ClusterPolicy generated by Helm chart is not valid

### ISSUE THREAD

**Issue by mkjpryor** [NVIDIA/gpu-operator#478]
### 1. Issue or feature description

For certain combinations of values, the gpu-operator Helm chart produces a `ClusterPolicy` that does not validate against the schema from the CRD. Helm itself and kubectl apply seem to be happy, but server-side apply fails.

This means that tools that use server-side apply, such as Argo CD in certain configurations, cannot write the `ClusterPolicy`.

In particular, values that should be either rendered as empty lists/objects, or not rendered at all, are rendered as null.

### 2. Steps to reproduce the issue

```sh
$ helm template nvidia-gpu-operator gpu-operator --repo https://nvidia.github.io/gpu-operator --version v22.9.1 -f values-test.yaml | kubectl apply --server-side=true -f - 

serviceaccount/gpu-operator serverside-applied
clusterrole.rbac.authorization.k8s.io/gpu-operator serverside-applied
clusterrolebinding.rbac.authorization.k8s.io/gpu-operator serverside-applied
deployment.apps/gpu-operator serverside-applied
The ClusterPolicy "cluster-policy" is invalid: spec.devicePlugin.config: Invalid value: "null": spec.devicePlugin.config in body must be of type object: "null"
```

```yaml
# values-test.yaml

dcgm:
  repository: nvcr.io/nvidia/cloud-native
dcgmExporter:
  repository: nvcr.io/nvidia/k8s
devicePlugin:
  repository: nvcr.io/nvidia
driver:
  manager:
    repository: nvcr.io/nvidia/cloud-native
  repository: nvcr.io/nvidia
gds:
  repository: nvcr.io/nvidia/cloud-native
gfd:
  repository: nvcr.io/nvidia
migManager:
  repository: nvcr.io/nvidia/cloud-native
nfd:
  enabled: false
nodeStatusExporter:
  enabled: true
  repository: nvcr.io/nvidia/cloud-native
operator:
  initContainer:
    repository: nvcr.io/nvidia
  repository: nvcr.io/nvidia
sandboxDevicePlugin:
  repository: nvcr.io/nvidia
toolkit:
  env:
  - name: CONTAINERD_CONFIG
    value: /etc/containerd/conf.d/nvidia.toml
  repository: nvcr.io/nvidia/k8s
validator:
  repository: nvcr.io/nvidia/cloud-native
vfioManager:
  driverManager:
    repository: nvcr.io/nvidia/cloud-native
  repository: nvcr.io/nvidia
vgpuDeviceManager:
  repository: nvcr.io/nvidia/cloud-native
vgpuManager:
  driverManager:
    repository: nvcr.io/nvidia/cloud-native
  repository: ""
```

### 3. Information to [attach](https://help.github.com/articles/file-attachments-on-issues-and-pull-requests/) (optional if deemed irrelevant)

N/A
