### ISSUE TITLE
Cannot load all gpus on a worker node when installing gpu-operator with helm on rke2 cluster.

### ISSUE THREAD

**Issue by zeddit** [NVIDIA/gpu-operator#492]
I am using helm to install gpu-operator on a rke2 cluster, with chart version 22.9.2
The chart can be installed successfully and the nvidia-operator-validator give the results of `all validations are successful`, thus I think it works fine under its expected behavior.

However, the number of gpus found by the gpu-operator is not correct.
I have 8 gpus on each worker nodes, but only 6 of them can be loaded by the operator. and all of my worker nodes loads a same number of 6 gpus, which is super wired.

I do some checking. 
The `kubectl describe node worker1` gives the allocatable resources like below:
```
Allocatable:
  cpu:                80
  ephemeral-storage:  99834798412
  hugepages-1Gi:      0
  hugepages-2Mi:      0
  memory:             990785300Ki
  nvidia.com/gpu:     6 #should be 8 here
```
In worker node host system, do `lspci | grep -i nvidia`, I could find 8 pcie lane.

And in nvidia-driver-daemonset pod:
I can find 8 gpu devices under /dev/ directory, i.e. nvidia0, nvidia1,...., nvidia7
however, nvidia-smi can only find 6 gpus, like:
```
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 510.108.03   Driver Version: 510.108.03   CUDA Version: 11.6     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA RTX A6000    On   | 00000000:03:00.0 Off |                  Off |
| 30%   28C    P8    24W / 300W |      1MiB / 49140MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   1  NVIDIA RTX A6000    On   | 00000000:04:00.0 Off |                  Off |
| 30%   27C    P8    17W / 300W |      1MiB / 49140MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   2  NVIDIA RTX A6000    On   | 00000000:0B:00.0 Off |                  Off |
| 30%   28C    P8    18W / 300W |      1MiB / 49140MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   3  NVIDIA RTX A6000    On   | 00000000:0C:00.0 Off |                  Off |
| 30%   27C    P8    30W / 300W |      1MiB / 49140MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   4  NVIDIA RTX A6000    On   | 00000000:13:00.0 Off |                  Off |
| 30%   26C    P8     6W / 300W |      1MiB / 49140MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   5  NVIDIA RTX A6000    On   | 00000000:1B:00.0 Off |                  Off |
| 30%   26C    P8    16W / 300W |      1MiB / 49140MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+
```

attaching the values of the chart:
```
nfd:
  enabled: true
mig:
  strategy: single
psp:
  enabled: false
driver:
  enabled: true
  repository: nvcr.io/nvidia
  #version: "525.60.13"
  version: "510.108.03"
  rdma:
    enabled: false
    useHostMofed: false
operator:
  defaultRuntime: containerd
toolkit:
  enabled: true
  env:
  - name: CONTAINERD_CONFIG
    value: /var/lib/rancher/rke2/agent/etc/containerd/config.toml
  - name: CONTAINERD_SOCKET
    value: /run/k3s/containerd/containerd.sock
  - name: CONTAINERD_RUNTIME_CLASS
    value: nvidia
  - name: CONTAINERD_SET_AS_DEFAULT
    value: "true"
```
