### ISSUE TITLE
[BUG]: console-plugin-nvidia-gpu

### ISSUE THREAD

**Issue by grvn** [NVIDIA/gpu-operator#496]
_The template below is mostly useful for bug reports and support questions. Feel free to remove anything which doesn't apply to you and add more information where it makes sense._

### 1. Quick Debug Checklist
- [x] Are you running Kubernetes v1.13+?
- [x] Are you running Docker (>= 18.06) or CRIO (>= 1.13+)?
- [x] Are you running on OpenShift 4.11?
- [x] Have you search for your issue and not found it?

### 1. Issue or feature description
the 0.2.3 version of the helm chart "console-plugin-nvidia-gpu-0.2.3.tgz" available at https://rh-ecosystem-edge.github.io/console-plugin-nvidia-gpu failes to install with the error
```
error: map[string]interface {}(nil): yaml: unmarshal errors:
  line 13: mapping key "app.kubernetes.io/instance" already defined at line 9
```

Forcing Helm to render it in debug mode shows that the label `app.kubernetes.io/instance` is written twice to several objects:
```
---
# Source: console-plugin-nvidia-gpu/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: RELEASE-NAME-console-plugin-nvidia-gpu
  labels:
    helm.sh/chart: console-plugin-nvidia-gpu-0.2.3
    app.kubernetes.io/name: console-plugin-nvidia-gpu
    app.kubernetes.io/instance: RELEASE-NAME
    app.kubernetes.io/version: "latest"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: console-plugin-nvidia-gpu
    app.kubernetes.io/instance: console-plugin-nvidia-gpu
    app.kubernetes.io/part-of: console-plugin-nvidia-gpu
data:
  dcgm-metrics.csv: |
    DCGM_FI_PROF_GR_ENGINE_ACTIVE, gauge, gpu utilization.
    DCGM_FI_DEV_MEM_COPY_UTIL, gauge, mem utilization.
    DCGM_FI_DEV_ENC_UTIL, gauge, enc utilization.
    DCGM_FI_DEV_DEC_UTIL, gauge, dec utilization.
    DCGM_FI_DEV_POWER_USAGE, gauge, power usage.
    DCGM_FI_DEV_POWER_MGMT_LIMIT_MAX, gauge, power mgmt limit.
    DCGM_FI_DEV_GPU_TEMP, gauge, gpu temp.
    DCGM_FI_DEV_SM_CLOCK, gauge, sm clock.
    DCGM_FI_DEV_MAX_SM_CLOCK, gauge, max sm clock.
    DCGM_FI_DEV_MEM_CLOCK, gauge, mem clock.
    DCGM_FI_DEV_MAX_MEM_CLOCK, gauge, max mem clock.
---
# Source: console-plugin-nvidia-gpu/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: RELEASE-NAME-console-plugin-nvidia-gpu
  labels:
    helm.sh/chart: console-plugin-nvidia-gpu-0.2.3
    app.kubernetes.io/name: console-plugin-nvidia-gpu
    app.kubernetes.io/instance: RELEASE-NAME
    app.kubernetes.io/version: "latest"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: console-plugin-nvidia-gpu
    app.kubernetes.io/instance: console-plugin-nvidia-gpu
    app.kubernetes.io/part-of: console-plugin-nvidia-gpu
  annotations:
    service.alpha.openshift.io/serving-cert-secret-name: plugin-serving-cert
spec:
  ports:
  - name: 9443-tcp
    protocol: TCP
    port: 9443
    targetPort: 9443
  selector:
    app.kubernetes.io/name: console-plugin-nvidia-gpu
    app.kubernetes.io/instance: RELEASE-NAME
  type: ClusterIP
  sessionAffinity: None
---
# Source: console-plugin-nvidia-gpu/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: RELEASE-NAME-console-plugin-nvidia-gpu
  labels:
    helm.sh/chart: console-plugin-nvidia-gpu-0.2.3
    app.kubernetes.io/name: console-plugin-nvidia-gpu
    app.kubernetes.io/instance: RELEASE-NAME
    app.kubernetes.io/version: "latest"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: console-plugin-nvidia-gpu
    app.kubernetes.io/instance: console-plugin-nvidia-gpu
    app.kubernetes.io/part-of: console-plugin-nvidia-gpu
    app.openshift.io/runtime-namespace: console-plugin-nvidia-gpu
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: console-plugin-nvidia-gpu
      app.kubernetes.io/instance: RELEASE-NAME
  template:
    metadata:
      labels:
        app.kubernetes.io/name: console-plugin-nvidia-gpu
        app.kubernetes.io/instance: RELEASE-NAME
    spec:
      securityContext:
        runAsNonRoot: true
      containers:
      - name: console-plugin-nvidia-gpu
        image: "quay.io/edge-infrastructure/console-plugin-nvidia-gpu:latest"
        imagePullPolicy: Always
        securityContext:
          allowPrivilegeEscalation: false
        ports:
        - containerPort: 9443
          protocol: TCP
        volumeMounts:
        - name: plugin-serving-cert
          readOnly: true
          mountPath: /var/serving-cert
        resources:
            {}
      volumes:
      - name: plugin-serving-cert
        secret:
          secretName: plugin-serving-cert
          defaultMode: 420
      - name: nginx-conf
        configMap:
          name: nginx-conf
          defaultMode: 420
      restartPolicy: Always
      dnsPolicy: ClusterFirst
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
---
# Source: console-plugin-nvidia-gpu/templates/consoleplugin.yaml
apiVersion: console.openshift.io/v1alpha1
kind: ConsolePlugin
metadata:
  name: RELEASE-NAME-console-plugin-nvidia-gpu
  labels:
    helm.sh/chart: console-plugin-nvidia-gpu-0.2.3
    app.kubernetes.io/name: console-plugin-nvidia-gpu
    app.kubernetes.io/instance: RELEASE-NAME
    app.kubernetes.io/version: "latest"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: console-plugin-nvidia-gpu
    app.kubernetes.io/instance: console-plugin-nvidia-gpu
    app.kubernetes.io/part-of: console-plugin-nvidia-gpu
spec:
  displayName: 'Console Plugin NVIDIA GPU Template'
  service:
    name: RELEASE-NAME-console-plugin-nvidia-gpu
    namespace: default
    port: 9443
    basePath: '/'
---
# Source: console-plugin-nvidia-gpu/templates/tests/test-plugin-service.yaml
apiVersion: v1
kind: Pod
metadata:
  name: "RELEASE-NAME-service-test"
  annotations:
    "helm.sh/hook": test
spec:
  containers:
    - name: RELEASE-NAME-service-test
      image: quay.io/cilium/alpine-curl:v1.4.0
      imagePullPolicy: "Always"
      args:
        - -XGET
        - --silent
        - --fail
        - --insecure
        - https://RELEASE-NAME-console-plugin-nvidia-gpu.default.svc:9443/plugin-manifest.json
  restartPolicy: Never
```

### 2. Steps to reproduce the issue
Follow the instructions on https://docs.nvidia.com/datacenter/cloud-native/gpu-operator/archive/22.9.1/openshift/enable-gpu-op-dashboard.html
```
helm repo add rh-ecosystem-edge https://rh-ecosystem-edge.github.io/console-plugin-nvidia-gpu
helm repo update
helm install -n nvidia-gpu-operator console-plugin-nvidia-gpu rh-ecosystem-edge/console-plugin-nvidia-gpu
```

### 3. Cause of the error
The _helpers.tpl appends "app.kubernetes.io/instance" through "console-plugin-nvidia-gpu.labels" to multiple objects but Helm itself also sets this value to "app.kubernetes.io/instance: RELEASE-NAME" which creates the conflict.
