### ISSUE TITLE
GPU operator component compatiblity matrix does not work for all combinations it specifies

### ISSUE THREAD

**Issue by lrotim** [NVIDIA/gpu-operator#509]
### 1. Issue or feature description
We're using the gpu-operator helm chart to install and configure the operator. It is configured as an "umbrella chart" with the following files in directory structure.
`nvidia-gpu-operator`
  - `Chart.yaml`
  -  `values.yaml`

contents of `Chart.yaml`
```yaml
apiVersion: v2
version: 0.1.0
name: gpu-operator-custom
dependencies:
- name: gpu-operator
  version: v22.9.2
  repository: https://helm.ngc.nvidia.com/nvidia
```
and `values.yaml`
```yaml
gpu-operator:
  driver:
    version: "450.216.04"
    upgradePolicy:
      autoUpgrade: true
      drain:
        enable: true
        force: true
      gpuPodDeletion:
        force: true
    manager:
      env:
      - name: ENABLE_GPU_POD_EVICTION
        value: "true"
      - name: ENABLE_AUTO_DRAIN
        value: "true"
      - name: DRAIN_USE_FORCE
        value: "true"
      - name: DRAIN_POD_SELECTOR_LABEL
        value: ""
      - name: DRAIN_TIMEOUT_SECONDS
        value: "0s"
      - name: DRAIN_DELETE_EMPTYDIR_DATA
        value: "false"
  mig:
    strategy: "single"
  toolkit:
    enabled: "true"
  dcgmExporter:
    enabled: "false"
``` 
I've configured a bit more that may be necessary (enabling force to reduce the chance of hitting a block while testing it out)
The important part is the one configuring `driver.version` field to `450.216.04`. The table you provided [here](https://docs.nvidia.com/datacenter/cloud-native/gpu-operator/platform-support.html) says this should be compatible and a valid argument.

As I can see this results with creation of CRD `ClusterPolicy` (apiversion `nvidia.com/v1`). I'm guessing that the "controller" or operator pod is using this config to create other manifests. An important one is `nvidia-driver-daemonset`. This daemonset plays a key part in driver installation, and the images used for it are deduced from `driver.version` helm value of this chart. To be more precise a pod of `nvidia-driver-daemonset` consists of init container (`k8s-driver-manager`) and one main container (`nvidia-driver-ctr`). `driver.version` parameter is used by gpu-operator to deduce the exact images to be used by `nvidia-driver-ctr`. To be even more concrete, it seems that the "operator or controller" is generating this image in the following format (if we imagine to have access to the helm values of this chart) {{ .Values.driver.repository }}/{{ .Values.driver.image }}:{{ .Values.driver.version}}-ubuntu22.04

As far as I can see the "-ubuntu22.04" is hardcoded in the operator (in this specific version). To be even more concrete this leaves us with  `nvidia-driver-ctr` using image `nvcr.io/nvidia/driver:450.216.04-ubuntu22.04`, which does not exist. It only exists for ubuntu 20.04, which makes this config invalid. 

### 2. Steps to reproduce the issue

We deployed using argoCD, but running the following commands in `gpu-operator` dir we get the same result
```bash
helm dependency build .
helm template gpu-operator -n gpu-operator . > res.yaml
kubectl apply -n gpu-operator -f res.yaml
```

### 3. Additional Information 

I managed to bypass this limitations preparing custom build of the driver image, and getting a valid config and utilizing the GPU. It required rebuilding the driver image for the driver version `450.216.04` for ubuntu22.04.

As far as I can see, this limitation is true for all driver versions `<515.86.01` making this chart invalid for anything "older" than that.

I managed to build a valid image starting from Dockerfile [here](https://gitlab.com/nvidia/container-images/driver/-/blob/main/ubuntu22.04/Dockerfile). It would, however, be nice if you either
 - updated the [GPU Operator Component Matrix](https://docs.nvidia.com/datacenter/cloud-native/gpu-operator/platform-support.html#gpu-operator-component-matrix) to remove older versions
 - build and publish images on you registry `nvcr.io/nvidia/driver:450.216.04-ubuntu22.04`, `nvcr.io/nvidia/driver:470.161.03-ubuntu22.04` and `nvcr.io/nvidia/driver:515.86.01-ubuntu22.04`
 
 I'd vote for the latter
