### ISSUE TITLE
Node-by-node migration of k8s from docker to containerd with running toolkit leading to the inavailability of non-yet-upgraded nodes. 

### ISSUE THREAD

**Issue by punkerpunker** [NVIDIA/gpu-operator#533]
### 1. Issue or feature description

When migrating nodes from `docker` to `containerd` runtime node by node, after the first GPU-node upgrade, `nvidia-toolkit` assumed that the rest of the nodes are also running on the `containerd` engine. 

After that, `toolkit` changed the `/etc/containerd/config.toml` and restarted `containerd` for the nodes that HAVEN'T BEEN UPGRADED YET, led to the unavailability of all except the upgraded GPU-nodes in the cluster. 

I was expecting `toolkit` to take into account the node configuration of each node individually, rather than the described behaviour.

### 2. Steps to reproduce the issue

I spotted it while I was upgrading my `1.23.8` cluster running with the `docker` container engine to the `1.24.12` cluster with `containerd` container engine. I guess same might appear if you join a `containerd` node to the `docker` cluster.

**Comment by shivamerla** [comment]
@punkerpunker this is the current limitation with the gpu-operator that mixed runtime engines are not supported in the same cluster. We will look into enhancing to consider per node config. Unfortunately below workaround is required to achieve this today.

1. Stop gpu-operator, by running `kubectl scale deployment --replicas=0 gpu-operator -n gpu-operator'
2. Change updateStrategy of `nvidia-container-toolkit` Daemonset to `OnDelete` instead of `RollingUpdate`.
3. Edit `nvidia-container-toolkit` daemonset to mount containerd config file (/etc/containerd/config.toml), socket (/var/run/containerd.sock) file instead of docker socket/config files.
4. Edit `nvidia-container-toolkit` to change/add following env
  - `RUNTIME_ARGS` to use containerd config and socket files
  - `CONTAINERD_RUNTIME_CLASS` to "nvidia"
  -  `RUNTIME` to `containerd`.
5. None of the toolkit pods should restart with above settings as upgradeStrategy is set to `OnDelete`.
6. Perform cluster upgrade from docker engine to containerd, as each node reboots after the upgrade, toolkit pod will start with updated spec and configure for containerd.
7. After upgrade of all nodes is done, scale back gpu-operator deployment to replicas=1.

**Comment by punkerpunker** [comment]
Makes sense @shivamerla, thanks. I'll leave the tread open until I try the workaround you mention. I'll post once I have the results of the upgrade this way

**Comment by punkerpunker** [comment]
I confirm that solution works, however, I also had to mount `/etc/containerd/config.toml` and `/var/containerd/containerd.sock`:

1. Volumes: 
```
      - hostPath:
          path: /etc/containerd
          type: ""
        name: containerd-config
      - hostPath:
          path: /run/containerd
          type: ""
        name: containerd-socket
```

2. volumeMounts:
```
        - mountPath: /runtime/config-dir/
          name: containerd-config
        - mountPath: /runtime/sock-dir/
          name: containerd-socket
```

3. env:
```
        env:
        - name: RUNTIME_ARGS
          value: --socket /runtime/sock-dir/containerd.sock --config /runtime/config-dir/config.toml
        - name: RUNTIME
          value: containerd
        - name: CONTAINERD_RUNTIME_CLASS
          value: nvidia
```

Thanks for the help @shivamerla, we can close the issue I guess
