### ISSUE TITLE
Setup problem on Openshift 4.3

### ISSUE THREAD

**Issue by przem123** [NVIDIA/gpu-operator#55]
On my Openshift 4.3 I have two worker nodes with GeForce cards:
```
[root@worker01 ~]# lspci|grep -i nvidia
06:00.0 VGA compatible controller: NVIDIA Corporation GP107 [GeForce GTX 1050 Ti] (rev a1)
```

I installed the Nvdia GPU Operator via Openshift Web console from Operator Hub. When I check the namespace (`gpu`) I see only these two operators:
```
[root@worker01 ~]# oc get pods -n gpu
NAME                            READY   STATUS    RESTARTS   AGE
gpu-operator-694b7874-2xrwm     1/1     Running   0          10h
nfd-operator-5666c6f94d-9lvr2   1/1     Running   0          10h
```
I dont see any change in the output of  `oc describe node`.
What should I do next ? When I click on the Web console on `Create instance` (ClusterPolicy) I can see this yaml file:

```
apiVersion: nvidia.com/v1
kind: ClusterPolicy
metadata:
  name: nvidia-gpu
  namespace: gpu
spec:
  size: 3
status:
  state: N/A
```

Do I need to specify something in the yaml file ? What should I do next ? I want to use my Nvidia cards in the Openshift cluster.
