### ISSUE TITLE
nvidia container toolkit stay in waiting to start

### ISSUE THREAD

**Issue by yingding** [NVIDIA/gpu-operator#552]
_The template below is mostly useful for bug reports and support questions. Feel free to remove anything which doesn't apply to you and add more information where it makes sense._

### 1. Quick Debug Checklist
- [ ] Are you running on an Ubuntu 18.04 node?
- [x] Are you running Kubernetes v1.13+?
- [ ] Are you running Docker (>= 18.06) or CRIO (>= 1.13+)?
- [ ] Do you have `i2c_core` and `ipmi_msghandler` loaded on the nodes?
- [x] Did you apply the CRD (`kubectl describe clusterpolicies --all-namespaces`)

### 1. Issue or feature description

On a Rancher 1.24 Cluster, deployed gpu-operator `v23.3.2` with helm3, 
![Screenshot 2023-07-17 at 13 34 55](https://github.com/NVIDIA/gpu-operator/assets/1073701/17946ae7-7c16-448c-8160-aae07ba1734a)

### 2. Steps to reproduce the issue

```shell
chart_version=v23.3.2;
name_space="gpu-operator";
release_name="gpu-operator";
confpath="/values.yaml";
helm install -f ${confpath} --wait ${release_name} -n ${name_space} nvidia/gpu-operator --version ${chart_version}
```

My values.yaml
```yaml
mig:
  strategy: single

driver:
  enabled: true
  version: "535.54.03"

toolkit:
  enabled: true
  env:
    - name: CONTAINERD_CONFIG
      value: /var/lib/rancher/rke2/agent/etc/containerd/config.toml.tmpl
    - name: CONTAINERD_SOCKET
      value: /run/k3s/containerd/containerd.sock
    - name: CONTAINERD_RUNTIME_CLASS
      value: nvidia
    - name: CONTAINERD_SET_AS_DEFAULT
      # true for all pod in this runtime, otherwise only pod with the "runtimeClassName: nvidia"
      value: "false"
    - name: CONTAINERD_RESTART_MODE
      value: systemd
```

I haven't installed `nvidia container toolkit` manually, thought the gpu-operator shall be able to install all the driver and toolkit itself.
