### ISSUE TITLE
 The GPU Operator driver build fails on GCP when using Ubuntu 22.04.

### ISSUE THREAD

**Issue by uniit** [NVIDIA/gpu-operator#564]
### 1. Quick Debug Information
* OS/Version: Ubuntu 22.04
* Kernel Version: 
```
Linux version 5.19.0-1030-gcp (buildd@bos03-amd64-050) (x86_64-linux-gnu-gcc-12 (Ubuntu 12.1.0-2ubuntu1~22.04) 12.1.0, GNU ld (GNU Binutils for Ubuntu) 2.38) #32~22.04.1-Ubuntu SMP Thu Jul 13 09:36:23 UTC 2023
```
* GPU Operator Version: GPU Operator 23.3.2 Release

### 2. Issue or feature description
The issue with the GPU Operator is that it cannot build Nvidia drivers on GCP with Ubuntu 22.04 due to the usage of the x86_64-linux-gnu-gcc-12 compiler in the build process. This incompatibility is causing the build to fail.
```
warning: the compiler differs from the one used to build the kernel
  The kernel was built by: x86_64-linux-gnu-gcc-12 (Ubuntu 12.1.0-2ubuntu1~22.04) 12.1.0
  You are using:           cc (Ubuntu 11.3.0-1ubuntu1~22.04) 11.3.0
```

Ubuntu 22.04 on AWS works well because it uses a similar major version of the compiler as the one used on the generic kernels. This similarity in compiler versions allows the GPU Operator to build Nvidia drivers successfully on AWS with Ubuntu 22.04.
```
Linux version 5.15.0-1034-aws (buildd@lcy02-amd64-114) (gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0, GNU ld (GNU Binutils for Ubuntu) 2.34) #38~20.04.1-Ubuntu SMP Wed Mar 29 19:48:16 UTC 2023
```

### 3. Steps to reproduce the issue
1. Create GCP instance (N1 + NVIDIA T4) with Ubuntu 22.04.
2. Install k3s:
```
curl -sfL https://get.k3s.io | sh - 
```
Install GPU Operator with the followiing helm values:
```
USER-SUPPLIED VALUES:
driver:
  enabled: true
operator:
  cleanupCRD: true
  defaultRuntime: containerd
toolkit:
  env:
  - name: CONTAINERD_CONFIG
    value: /var/lib/rancher/k3s/agent/etc/containerd/config.toml.tmpl
  - name: CONTAINERD_SOCKET
    value: /run/k3s/containerd/containerd.sock
  - name: CONTAINERD_RUNTIME_CLASS
    value: nvidia
  - name: CONTAINERD_SET_AS_DEFAULT
    value: "true"
```
### 4. Question:

Can I easily include gcc-12 in the driver image and change the build instructions to utilize it, either through an environment variable or by overriding the initial command?

Is there a plan to introduce support for Ubuntu 22.04 on GCP?
