### ISSUE TITLE
InvalidImageName when specifying the driver version in the spec.driver.version property

### ISSUE THREAD

**Issue by koflerm** [NVIDIA/gpu-operator#585]
### 1. Quick Debug Information
* Container Runtime Type/Version(e.g. Containerd, CRI-O, Docker): CRI-O
* K8s Flavor/Version(e.g. K8s, OCP, Rancher, GKE, EKS): OCP 4.11.43
* GPU Operator Version: 23.6.1

### 2. Issue or feature description
When specifying a driver version in the ClusterPolicy object in the spec.driver.version property, the driver-daemonset pods are crashing with the error "InvalidImageName". This is caused by the image used for the driver container, which has the following format: "image: '/:525.60.13-rhcos4.11'". Obviously, the registry, repository and image is missing in the reference. The image value should be set to "nvcr.io/nvidia/driver:525.60.13-rhcos4.11".

### 3. Steps to reproduce the issue
- Set the spec.driver.version property of the ClusterPolicy CR.

### 4. Information to [attach](https://help.github.com/articles/file-attachments-on-issues-and-pull-requests/) (optional if deemed irrelevant)

 - [x ] ClusterPolicy YAML

```
apiVersion: nvidia.com/v1
kind: ClusterPolicy
metadata:
  name: gpu-cluster-policy
spec:
  vgpuDeviceManager:
    config:
      default: default
    enabled: true
  migManager:
    enabled: true
  operator:
    defaultRuntime: crio
    initContainer: {}
    runtimeClass: nvidia
    use_ocp_driver_toolkit: true
  dcgm:
    enabled: true
  gfd:
    enabled: true
  dcgmExporter:
    config:
      name: nvidia-dcgm-exporter-custom-config
    enabled: true
    serviceMonitor:
      enabled: true
  driver:
    certConfig:
      name: ''
    enabled: true
    kernelModuleConfig:
      name: ''
    licensingConfig:
      configMapName: ''
      nlsEnabled: false
    repoConfig:
      configMapName: ''
    version: 525.60.13
    virtualTopology:
      config: ''
  devicePlugin:
    config:
      default: ''
      name: ''
    enabled: true
    env:
      - name: DEVICE_LIST_STRATEGY
        value: volume-mounts
  mig:
    strategy: mixed
  sandboxDevicePlugin:
    enabled: true
  validator:
    plugin:
      env:
        - name: WITH_WORKLOAD
          value: 'true'
  nodeStatusExporter:
    enabled: true
  daemonsets:
    updateStrategy: RollingUpdate
  sandboxWorkloads:
    defaultWorkload: container
    enabled: false
  vgpuManager:
    enabled: false
  vfioManager:
    enabled: true
  toolkit:
    enabled: true
    env:
      - name: ACCEPT_NVIDIA_VISIBLE_DEVICES_ENVVAR_WHEN_UNPRIVILEGED
        value: 'false'
      - name: ACCEPT_NVIDIA_VISIBLE_DEVICES_AS_VOLUME_MOUNTS
        value: 'true'
    installDir: /usr/local/nvidia
status:
  namespace: nvidia-gpu-operator
  state: notReady
```
