### ISSUE TITLE
Waiting for gpu node to be ready before scheduling pods using NVML

### ISSUE THREAD

**Issue by easyrider14** [NVIDIA/gpu-operator#615]
Hi everyone

I face an issue with gpu-operator and scaling of my K8S cluster
When adding a GPU node to cluster, gpu-operator will, amon others things, install container runtime and drivers
I've got a daemonset which uses NVML, but it is scheduled on the newly added gpu node as soon as it is available. But the driver is not ready, and initializing NVML fails. The container in my pod exits, but the pod is restarted and not deleted/created, so NVML initialization still fails. Which criteria should I use in mu daemonset definition to make sur my pod will be able to initialize NVML and run correctly when it will be scheduled on the node ?

Thanks

**Comment by tariq1890** [comment]
You can add consider adding the `gpu-operator-validator` as an init container to your daemonset. This way, the daemonset would block on the nvidia-driver-daemonset transitioning to the Ready/Running state 

Sample snippet 
```
      initContainers:
      - name: driver-validation
        image: "nvcr.io/nvidia/cloud-native/gpu-operator-validator:v23.9.0"
        imagePullPolicy: IfNotPresent
        command: ['sh', '-c']
        args: ["nvidia-validator"]
        env:
          - name: WITH_WAIT
            value: "true"
          - name: COMPONENT
            value: driver
        securityContext:
          privileged: true
          seLinuxOptions:
            level: "s0"
        volumeMounts:
          - name: driver-install-path
            mountPath: /run/nvidia/driver
            mountPropagation: HostToContainer
          - name: run-nvidia-validations
            mountPath: /run/nvidia/validations
            mountPropagation: Bidirectional
          - name: host-root
            mountPath: /host
            readOnly: true
            mountPropagation: HostToContainer
          - name: host-dev-char
            mountPath: /host-dev-char
```
