### ISSUE TITLE
Docs for `CONTAINERD_CONFIG` for RKE2 + containerd should recommend writing to `/var/lib/rancher/rke2/agent/etc/containerd/config.toml`

### ISSUE THREAD

**Issue by Guent4** [NVIDIA/gpu-operator#623]
### 1. Quick Debug Information
* OS/Version(e.g. RHEL8.6, Ubuntu22.04): Ubuntu 22.04.2 LTS
* Kernel Version: 5.15.0-75-generic
* Container Runtime Type/Version(e.g. Containerd, CRI-O, Docker): containerd
* K8s Flavor/Version(e.g. K8s, OCP, Rancher, GKE, EKS): RKE2
* GPU Operator Version: v23.9.0

### 2. Issue or feature description
In the [docs](https://docs.nvidia.com/datacenter/cloud-native/gpu-operator/latest/getting-started.html#custom-configuration-for-runtime-containerd) for custom runtime configuration for containerd + RKE2, the following settings are suggested:
```
toolkit:
   env:
   - name: CONTAINERD_CONFIG
     value: /var/lib/rancher/rke2/agent/etc/containerd/config.toml.tmpl
   - name: CONTAINERD_SOCKET
     value: /run/k3s/containerd/containerd.sock
   - name: CONTAINERD_RUNTIME_CLASS
     value: nvidia
   - name: CONTAINERD_SET_AS_DEFAULT
     value: "true"
```
These settings do not work well when you need to set internal registries' config for Rancher ([docs](https://docs.rke2.io/install/containerd_registry_configuration)).  Instead, we need to set `CONTAINERD_CONFIG` to `/var/lib/rancher/rke2/agent/etc/containerd/config.toml`.

What RKE2 does under the hood is it takes the credentials you included in the `/etc/rancher/rke2/registries.yaml` file and then populates it in `config.toml`.  This means that since the `gpu-operator` writes its config in `config.toml.tmpl` which is then used to generate `config.toml`, the private registry auth settings gets overwritten.

Having the `gpu-operator` write to `config.toml.tmpl` seems like the right thing to do especially considering that the top of `config.toml` has a warning stating:
```
# File generated by rke2. DO NOT EDIT. Use config.toml.tmpl instead.
```
but unfortunately, RKE2 itself writes directly to `config.toml`.

### 3. Steps to reproduce the issue
1. Set up a RKE2 cluster and deploy `gpu-operator` on it with a node that has a GPU and a node that DOESN'T have a GPU
2. SSH into both nodes and edit `/etc/rancher/rke2/registries.yaml`:
    ```
    configs:
      "my.registry":
        auth:
          auth: "FOOBAR"
    mirrors:
    ```
    (note that the actual registry and auth token value don't matter)
3. Restart RKE2: `sudo systemctl restart rke2-agent.service` if you're on a worker, else restart `rke2-server.service`
4. Compare `/var/lib/rancher/rke2/agent/etc/containerd/config.toml` on the GPU node and the non-GPU node.  Only the latter will contain the registry + auth token.
