### ISSUE TITLE
Is the NVIDIADriver CRD (manager and startupProbe fields) merged with the default?

### ISSUE THREAD

**Issue by skirsten** [NVIDIA/gpu-operator#630]
Nowhere does it mention what happens to fields such as `manager` in the NVIDIADriver CRD if its empty.

In the [docs](https://docs.nvidia.com/datacenter/cloud-native/gpu-operator/latest/gpu-driver-configuration.html) and [examples](https://github.com/NVIDIA/gpu-operator/blob/55493552608211200db08e6ae34e13c865a368a9/config/samples/nvidia_v1alpha1_nvidiadriver.yaml) an empty object is provided:

```yaml
manager: {}
```

But the ["default" NVIDIADriver](https://github.com/NVIDIA/gpu-operator/blob/55493552608211200db08e6ae34e13c865a368a9/deployments/gpu-operator/templates/nvidiadriver.yaml#L3) includes the whole definition for the `manager` as well as `startupProbe`:

```yaml
manager: 
  env:
  - name: ENABLE_GPU_POD_EVICTION
    value: "true"
  - name: ENABLE_AUTO_DRAIN
    value: "false"
  - name: DRAIN_USE_FORCE
    value: "false"
  - name: DRAIN_POD_SELECTOR_LABEL
    value: ""
  - name: DRAIN_TIMEOUT_SECONDS
    value: 0s
  - name: DRAIN_DELETE_EMPTYDIR_DATA
    value: "false"
  image: k8s-driver-manager
  imagePullPolicy: IfNotPresent
  repository: nvcr.io/nvidia/cloud-native
  version: v0.6.5
startupProbe: 
  failureThreshold: 120
  initialDelaySeconds: 60
  periodSeconds: 10
  timeoutSeconds: 60
```

I really don't want to have this in the CRD and have to update it so I am hoping that if the manager and startupProbe is not provided (or empty) it will default to that. Can somebody confirm or deny this?
