### ISSUE TITLE
toolkit uses docker runtime, when containerd args are specified

### ISSUE THREAD

**Issue by nonoy-suguitan** [NVIDIA/gpu-operator#683]
I have a simple k8s cluster using v1.23 and I attempt to install the gpu operator on it; specifying to use the containerd args:

```
eksctl create cluster \
--name test-gpu-cluster-eksctl \
--version 1.23 \
--region us-east-1 \
--nodegroup-name gpu-nodes \
--node-type g4dn.xlarge \
--nodes 1

helm install --wait gpu-operator -n gpu-operator --create-namespace \
  nvidia/gpu-operator \
    --set 'toolkit.env[0].name=CONTAINERD_CONFIG' \
    --set 'toolkit.env[0].value=/etc/containerd/config.toml' \
    --set 'toolkit.env[1].name=CONTAINERD_SOCKET' \
    --set 'toolkit.env[1].value=/run/containerd/containerd.sock' \
    --set 'toolkit.env[2].name=CONTAINERD_RUNTIME_CLASS' \
    --set 'toolkit.env[2].value=nvidia' \
    --set 'toolkit.env[3].name=CONTAINERD_SET_AS_DEFAULT' \
    --set-string 'toolkit.env[3].value=true'
```

The install is successful but inspecting the toolkit's daemonset shows that it's setting the `RUNTIME` environment variable to docker, instead of containerd.

```
        env:
        - name: ROOT
          value: /usr/local/nvidia
        - name: RUNTIME_ARGS
        - name: NVIDIA_CONTAINER_RUNTIME_MODES_CDI_DEFAULT_KIND
          value: management.nvidia.com/gpu
        - name: NVIDIA_VISIBLE_DEVICES
          value: void
        - name: CONTAINERD_CONFIG
          value: /etc/containerd/config.toml
        - name: CONTAINERD_SOCKET
          value: /run/containerd/containerd.sock
        - name: CONTAINERD_RUNTIME_CLASS
          value: nvidia
        - name: CONTAINERD_SET_AS_DEFAULT
          value: "true"
        - name: RUNTIME
          value: docker
        - name: DOCKER_CONFIG
          value: /runtime/config-dir/daemon.json
        - name: DOCKER_SOCKET
          value: /runtime/sock-dir/docker.sock
```

Is there a way I can I install the toolkit to use the containerd runtime instead?
