### ISSUE TITLE
Run as nonRoot and set automountServiceAccountToken to false

### ISSUE THREAD

**Issue by ethan-young-vgm** [NVIDIA/gpu-operator#694]
We have implemented GPU Operator on our AKS cluster, and it is working great.
Few issues though. Azure is lighting up with high security vulnerabilities due to running the containers as root and auto mounting the service account token to the container.

We have already fixed these issues for everything else and even had to switch Kafka helm chart providers... 
I don't see an option in GPU Operator's helm chart to configure these two settings. 

I know this is not just on AKS as I saw others from other cloud providers saying the same with other helm charts, so my question is, will this be added in the future or is this even something that can be done with GPU Operator?

**Comment by elezar** [comment]
@shivamerla is this related to our discussion yesterday?

**Comment by caiobegotti** [comment]
hey folks 👋 not just about running as non-root but i'm wondering what would be needed/exempted from a spec like below for the gpu-operator?
```
securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL
  privileged: false
  seccompProfile:
    type: RuntimeDefault
```
i understand it may need certain capabilities etc but i don't which ones to whitelist or something else the gpu-operator needs that requires some root-level of access
