### ISSUE TITLE
Remove close dependence on NFD

### ISSUE THREAD

**Issue by superbrothers** [NVIDIA/gpu-operator#77]
GPU Operator uses the `feature.node.kubernetes.io/pci-10de.present` label created by NFD to determine GPU nodes, which cannot be changed. To remove the dependency on NFD, I suggest extending the ClusterPolicy CR as follows:

```yaml
apiVersion: nvidia.com/v1
kind: ClusterPolicy
metadata:
  name: cluster-policy
spec:
  nodeSelector:     # <-- Here
    matchLabels:
      feature.node.kubernetes.io/pci-10de.present: "true"
  dcgmExporter:
    ...
```

The ability to customize GPU node decisions also makes it possible to set up different versions of components in different node groups.

---

I think it's good to use `feature.node.kubernetes.io/pci-10de.present` label by default as it is now.
