### ISSUE TITLE
How to specify different Strategy per node + is there a Strategy to discover GPU 'as is' ?

### ISSUE THREAD

**Issue by amir-bialek** [NVIDIA/gpu-operator#835]
On-prem k8s with 5 nodes.

At the current setting all node will have the time-slicing feature with 15gpu. as far as I can see it is working well.
Got a new requirement - training a module which will be on node X , and will use all the gpu. node X have 4 gpu's
And: training a module which will be on mode Y and will use GPU a,b and -c. node Y have 8 GPU's.

So need to expose the GPU on node X and Y , as they are - > not as a mix of time-slicing.

If anyone can help me with the correct configuration I will be very grateful.

* I can see the label on every node with : ``` nvidia.com/gpu.count: "4"``` So I know it is recognize the gpu's.

I deployed the operator via helm-chart with the following values to over-write the default:
```
operator:
  defaultRuntime: containerd

dcgmExporter:
  enabled: false

devicePlugin:
  config:
    name: time-slicing-config-all
    create: true
    default: "any"
    data:
      any: |-
        version: v1
        flags:
          migStrategy: none
        sharing:
          timeSlicing:
            resources:
            - name: nvidia.com/gpu
              replicas: 15

node-feature-discovery:
  worker:
    tolerations:
    < some tolerations..>

daemonsets:
  labels: {}
  annotations: {}
  priorityClassName: system-node-critical
  tolerations:
    < some tolerations..>


operator:
  tolerations:
    < some tolerations..>
```

Thanks.

**Comment by klueska** [comment]
Please see the documentation here for setting up node-specific configurations:
https://docs.nvidia.com/datacenter/cloud-native/gpu-operator/latest/gpu-sharing.html#applying-multiple-node-specific-configurations

**Comment by amir-bialek** [comment]
@klueska thank for the reference.
I can see this does explain how to set node-specific configuration and apply it with a label on the node.
I assume it is possible to set up both a 'default' and 'custom' conf, and if the node have the label of the custom it will get the custom conf, if not it will get the default?

One more Q, this does not show how can I use the GPU 'as is' for scenario 2: 
If a node have 8 gpu, and I want to train a module on 4 gpu. my only option is to use time-slicing and set the replica for 8 (manually?)

**Comment by amir-bialek** [comment]
@frittentheke thank you for the reply.
I will like to make sure I understand correctly:
If pod1 is set on node1, I can only slice <b> all </b> the gpu's on the node1 , and give pod1 a slice (or all the slices)?

The situation is that on node1 I have 4 gpu's. 
Can I not make pod1 use gpu 1 and 2, and pod 2 gpu 3 and 4?

**Comment by frittentheke** [comment]
> @frittentheke thank you for the reply. I will like to make sure I understand correctly: If pod1 is set on node1, I can only slice all the gpu's on the node1 , and give pod1 a slice (or all the slices)?
> The situation is that on node1 I have 4 gpu's. Can I not make pod1 use gpu 1 and 2, and pod 2 gpu 3 and 4?

To me that's currently the case with the operators capabilities, yes. 
You can only select a resource by `name`, so e.g. `nvidia.com/gpu` of which all will them be sliced. 

Maybe using MIG (Multi Instance GPU) is an option? See https://developer.nvidia.com/blog/improving-gpu-utilization-in-kubernetes/

In that case you could 

a) Create multiple smaller GPUs and use them non-shared
b) Apply time-slicing to a single MIG profile, e.g. `nvidia.com/mig-4g.40gb` if you really want to timeSlice and it makes sense for your application:

```
        version: v1
        flags:
          migStrategy: mixed
        sharing:
          timeSlicing:
            renameByDefault: true
            failRequestsGreaterThanOne: true
            resources:
            - name: "nvidia.com/mig-4g.40gb"
              replicas: 2
```
