### ISSUE TITLE
Question: How does GPU-operator run nvidia-container-runtime from inside a container.  

### ISSUE THREAD

**Issue by etherandrius** [NVIDIA/gpu-operator#90]
Question as the title. 
 - How does GPU-operator achieve running `nvidia-container-runtime` from within a  container?
 - How is docker configured to allow for this ?
 - Is the same possible while running only containerd (no docker) ?

I've looked over the docs, the ones I've found all assume the runtime is installed on the machine image and not inside the docker container.

**Comment by klueska** [comment]
The operator runs a daemonset called `container-toolkit` with the container from this project installed:
https://gitlab.com/nvidia/container-toolkit/container-config

When launching this container, the operator sets up the following mount from the host into the container:
```
      volumes:
        - name: docker-socket
          hostPath:
            path: /var/run/docker.sock
        - name: nvidia-install-path
          hostPath:
            path: /run/nvidia
        - name: docker-config
          hostPath:
            path: /etc/docker
        - name: nvidia-local
          hostPath:
            path: /usr/local/nvidia
        - name: crio-hooks
          hostPath:
            path: /etc/containers/oci/hooks.d
```

The container itself, has the full `nvidia-docker` stack with all of its bins and libs installed inside of it at standard locations (i.e. `/usr/local/bin` and `/lib64`).

At startup, the `container-tooolkit` daemonset will run the following script:
https://gitlab.com/nvidia/container-toolkit/container-config/-/blob/master/src/run.sh

This script does the following:
1) Gather all of the components of the nvidia-docker stack and copy them under `/usr/local/nvidia/toolkit`
2) Update the contents of `/etc/docker/daemon.json` to configure the default container runtime to `/usr/local/nvidia/toolkit/nvidia-container-runtime`
3) Restart the docker daemon

Since `/usr/local/nvidia/`, `/etc/docker/`, and `/var/run/docker.sock` are all mounted from the host into the container, all of these changes are reflected on the host, and not just inside the container (even the docker restart).

With standalone containerd, a similar "patching" of `/etc/containerd/config.toml` could be done, but it is not yet supported by the operator. We plan to add support for this in the next release (`v1.4.0`).

We also plan to make the locations of the files mounted on the host configurable (at present it is assumed that the host path is the same as the container path for all mounts) so that non-root instances of docker / containerd can be supported (as is necessary for things like `microk8s`, which run their own instance of `containerd` from a `snap` sandbox).
