### ISSUE TITLE
OpenShift install - Required variables do not exist

### ISSUE THREAD

**Issue by rmkraus** [NVIDIA/gpu-operator#92]
### 1. Issue or feature description
Operator does not set the variables OPENSHIFT_VERSION or RHEL_VERSION on the nvidia-driver-daemonset daemonset. 

### 2. Steps to reproduce the issue
OpenShift 4.5.15
NVIDIA Operator 1.1.7-r2 that was OTA upgraded from 1.1.7 via Operator Hub.

1) allow operator to be ota updated
2) Delete existing clusterpolicy
3) Cluster policy definition:
```
apiVersion: nvidia.com/v1
kind: ClusterPolicy
metadata:
  name: cluster-policy
spec:
  dcgmExporter:
    image: dcgm-exporter
    repository: nvidia
    version: 1.7.2-2.0.0-rc.9-ubi8
  devicePlugin:
    image: k8s-device-plugin
    repository: nvidia
    version: 1.0.0-beta6-ubi8
  driver:
    image: driver
    repository: nvidia
    version: 450.80.02
  operator:
    defaultRuntime: crio
  toolkit:
    image: container-toolkit
    repository: nvidia
    version: 1.0.2-ubi8
```

### 3. Information to [attach](https://help.github.com/articles/file-attachments-on-issues-and-pull-requests/) (optional if deemed irrelevant)

The problem can be worked around by adding the following env variables to the driver daemonset definition:
```
          env:
            - name: OPENSHIFT_VERSION
              value: '4.5'
            - name: RHEL_VERSION
              value: '8.2'
```
