### ISSUE TITLE
How to use GPU Operator with MIG to configure 2 GPUs on one node separately

### ISSUE THREAD

**Issue by marlowsw** [NVIDIA/gpu-operator#981]
Issue:
I'm running the gpu operator in Openshift 4.14 (installed via operator hub) and I have a gpu node with 2 A100 40G gpus. My strategy is set to "single" and I'm currently running with the label

nvidia.com/mig.config: all-1g.5gb (This works fine)

My goal is to have one gpu set to 1g.5gb for 7 partitions and have the other gpu  set to a single large partition of 7g.40gb. This "should" work based on this chart: https://docs.nvidia.com/datacenter/tesla/mig-user-guide/index.html#a100-mig-profiles

I tried setting the following labels: 
nvidia.com/mig.config: all-enabled
nvidia.com/mig-7g.40gb.count: '1'
nvidia.com/mig-1g.5gb.count: '7'

and even though the mig manager will take this config and say it's "successful" it doesn't partition the gpus correctly.  It also breaks the operator and i'm left with failing pods.

The labels show on the node but it's status is:
status:
capacity:
cpu: '256'
ephemeral-storage: 468250412Ki
hugepages-1Gi: '0'
hugepages-2Mi: '0'
memory: 527902464Ki
nvidia.com/gpu: '14'
nvidia.com/mig-1g.5gb: '0'
pods: '250'
allocatable:
cpu: 255500m
ephemeral-storage: '430465837161'
hugepages-1Gi: '0'
hugepages-2Mi: '0'
memory: 526751488Ki
nvidia.com/gpu: '14'
nvidia.com/mig-1g.5gb: '0'
pods: '250'

Node Labels:
```
labels:

    feature.node.kubernetes.io/kernel-version.full: 5.14.0-284.69.1.el9_2.x86_64
    feature.node.kubernetes.io/cpu-cpuid.IBSFFV: 'true'
    nvidia.com/cuda.runtime.minor: '4'
    feature.node.kubernetes.io/cpu-rdt.RDTL3CA: 'true'
    feature.node.kubernetes.io/system-os_release.VERSION_ID.minor: '14'
    feature.node.kubernetes.io/pci-8086.sriov.capable: 'true'
    beta.kubernetes.io/os: linux
    feature.node.kubernetes.io/kernel-version.minor: '14'
    feature.node.kubernetes.io/cpu-cpuid.WBNOINVD: 'true'
    nvidia.com/gpu.machine: PowerEdge-R7525
    nvidia.com/gpu.memory: '4864'
    nvidia.com/gpu.engines.decoder: '0'
    feature.node.kubernetes.io/cpu-cpuid.AESNI: 'true'
    nvidia.com/cuda.runtime.major: '12'
    nvidia.com/gpu.deploy.dcgm-exporter: 'true'
    kubernetes.io/os: linux
    nvidia.com/gpu.deploy.device-plugin: 'true'
    nvidia.com/mig.config: all-1g.5gb
    nvidia.com/gpu.deploy.nvsm: 'true'
    feature.node.kubernetes.io/system-os_release.VERSION_ID.major: '4'
    feature.node.kubernetes.io/cpu-cpuid.IBSRDWROPCNT: 'true'
    nvidia.com/gpu.deploy.mig-manager: 'true'
    nvidia.com/gpu.family: ampere
    feature.node.kubernetes.io/cpu-cpuid.SHA: 'true'
    nvidia.com/gpu.sharing-strategy: none
    nvidia.com/mig.capable: 'true'
    nvidia.com/gpu.engines.jpeg: '0'
    feature.node.kubernetes.io/kernel-version.major: '5'
    feature.node.kubernetes.io/custom-rdma.available: 'true'
    feature.node.kubernetes.io/pci-102b.present: 'true'
    feature.node.kubernetes.io/cpu-cpuid.IBSOPSAM: 'true'
    nvidia.com/gpu.deploy.dcgm: 'true'
    nvidia.com/mig.config.state: success
    nvidia.com/gpu.engines.ofa: '0'
    feature.node.kubernetes.io/custom-rdma.capable: 'true'
    feature.node.kubernetes.io/pci-14e4.present: 'true'
    node-role.kubernetes.io/aaimsgpu: ''
    nvidia.com/gpu.slices.gi: '1'
    nvidia.com/cuda.driver-version.full: 550.54.15
    feature.node.kubernetes.io/kernel-version.revision: '0'
    feature.node.kubernetes.io/storage-nonrotationaldisk: 'true'
    nvidia.com/cuda.runtime-version.minor: '4'
    node-role.kubernetes.io/worker: ''
    nvidia.com/gpu.count: '14'
    nvidia.com/gpu.product: NVIDIA-A100-PCIE-40GB-MIG-1g.5gb
    zone: gpu
    nvidia.com/gfd.timestamp: '1725915690'
    nvidia.com/gpu.deploy.driver: 'true'
    nvidia.com/cuda.driver.minor: '54'
    nvidia.com/mps.capable: 'false'
    feature.node.kubernetes.io/cpu-cpuid.SSE4A: 'true'
    feature.node.kubernetes.io/pci-10de.sriov.capable: 'true'
    nvidia.com/gpu.deploy.operator-validator: 'true'
    feature.node.kubernetes.io/cpu-rdt.RDTCMT: 'true'
    feature.node.kubernetes.io/iommu-enabled: 'true'
    feature.node.kubernetes.io/pci-15b3.present: 'true'
    nvidia.com/gpu.deploy.container-toolkit: 'true'
    feature.node.kubernetes.io/cpu-cpuid.IBSOPCNTEXT: 'true'
    feature.node.kubernetes.io/system-os_release.RHEL_VERSION: '9.2'
    feature.node.kubernetes.io/kernel-config.NO_HZ_FULL: 'true'
    node.openshift.io/os_id: rhcos
    feature.node.kubernetes.io/pci-8086.present: 'true'
    nvidia.com/cuda.runtime-version.major: '12'
    feature.node.kubernetes.io/cpu-cpuid.ADX: 'true'
    feature.node.kubernetes.io/cpu-rdt.RDTMON: 'true'
    nvidia.com/gpu.slices.ci: '1'
    nvidia.com/cuda.driver.major: '550'
    feature.node.kubernetes.io/memory-numa: 'true'
    nvidia.com/mig-7g.40gb.count: '1'
    feature.node.kubernetes.io/cpu-cpuid.IBSOPCNT: 'true'
    feature.node.kubernetes.io/cpu-cpuid.IBSRIPINVALIDCHK: 'true'
    feature.node.kubernetes.io/cpu-cpuid.AVX2: 'true'
    kubernetes.io/hostname: nodenamehere
    nvidia.com/gpu.deploy.gpu-feature-discovery: 'true'
    feature.node.kubernetes.io/cpu-cpuid.SSE4: 'true'
    feature.node.kubernetes.io/system-os_release.ID: rhcos
    feature.node.kubernetes.io/cpu-cpuid.IBSBRNTRGT: 'true'
    region: aaimsgpu
    feature.node.kubernetes.io/system-os_release.OSTREE_VERSION: 414.92.202406041802-0
    nvidia.com/gpu.engines.copy: '1'
    beta.kubernetes.io/arch: amd64
    nvidia.com/gpu.deploy.node-status-exporter: 'true'
    feature.node.kubernetes.io/cpu-cpuid.IBS: 'true'
    kubernetes.io/arch: amd64
    nvidia.com/gpu.multiprocessors: '14'
    nvidia.com/mig.strategy: single
    nvidia.com/cuda.runtime-version.full: '12.4'
    nvidia.com/cuda.driver-version.minor: '54'
    feature.node.kubernetes.io/system-os_release.OPENSHIFT_VERSION: '4.14'
    nvidia.com/cuda.driver-version.revision: '15'
    nvidia.com/gpu.present: 'true'
    feature.node.kubernetes.io/pci-10de.present: 'true'
    feature.node.kubernetes.io/cpu-cpuid.IBSFETCHSAM: 'true'
    feature.node.kubernetes.io/kernel-selinux.enabled: 'true'
    feature.node.kubernetes.io/system-os_release.VERSION_ID: '4.14'
    feature.node.kubernetes.io/network-sriov.capable: 'true'
    nvidia.com/cuda.driver.rev: '15'
    nvidia.com/gpu.compute.minor: '0'
    nvidia.com/gpu.engines.encoder: '0'
    feature.node.kubernetes.io/cpu-rdt.RDTMBM: 'true'
    nvidia.com/mig-1g.5gb.count: '7'
    feature.node.kubernetes.io/cpu-hardware_multithreading: 'true'
    nvidia.com/cuda.driver-version.major: '550'
    feature.node.kubernetes.io/cpu-cpuid.SSE42: 'true'
    feature.node.kubernetes.io/cpu-cpuid.FMA3: 'true'
    feature.node.kubernetes.io/cpu-cpuid.AVX: 'true'
    nvidia.com/gpu.replicas: '1'
    feature.node.kubernetes.io/kernel-config.NO_HZ: 'true'
    nvidia.com/gpu.compute.major: '8'
```

```
nvidia-smi output:  
  

+-----------------------------------------------------------------------------------------+

| NVIDIA-SMI 550.54.15              Driver Version: 550.54.15      CUDA Version: 12.4     |

|-----------------------------------------+------------------------+----------------------+

| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |

| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |

|                                         |                        |               MIG M. |

|=========================================+========================+======================|

|   0  NVIDIA A100-PCIE-40GB          On  |   00000000:25:00.0 Off |                   On |

| N/A   30C    P0             67W /  250W |      87MiB /  40960MiB |     N/A      Default |

|                                         |                        |              Enabled |

+-----------------------------------------+------------------------+----------------------+

|   1  NVIDIA A100-PCIE-40GB          On  |   00000000:81:00.0 Off |                   On |

| N/A   30C    P0             69W /  250W |      87MiB /  40960MiB |     N/A      Default |

|                                         |                        |              Enabled |

+-----------------------------------------+------------------------+----------------------+

+-----------------------------------------------------------------------------------------+

| MIG devices:                                                                            |

+------------------+----------------------------------+-----------+-----------------------+

| GPU  GI  CI  MIG |                     Memory-Usage |        Vol|      Shared           |

|      ID  ID  Dev |                       BAR1-Usage | SM     Unc| CE ENC DEC OFA JPG    |

|                  |                                  |        ECC|                       |

|==================+==================================+===========+=======================|

|  0    7   0   0  |              12MiB /  4864MiB    | 14      0 |  1   0    0    0    0 |

|                  |                 0MiB /  8191MiB  |           |                       |

+------------------+----------------------------------+-----------+-----------------------+

|  0    8   0   1  |              12MiB /  4864MiB    | 14      0 |  1   0    0    0    0 |

|                  |                 0MiB /  8191MiB  |           |                       |

+------------------+----------------------------------+-----------+-----------------------+

|  0    9   0   2  |              12MiB /  4864MiB    | 14      0 |  1   0    0    0    0 |

|                  |                 0MiB /  8191MiB  |           |                       |

+------------------+----------------------------------+-----------+-----------------------+

|  0   10   0   3  |              12MiB /  4864MiB    | 14      0 |  1   0    0    0    0 |

|                  |                 0MiB /  8191MiB  |           |                       |

+------------------+----------------------------------+-----------+-----------------------+

|  0   11   0   4  |              12MiB /  4864MiB    | 14      0 |  1   0    0    0    0 |

|                  |                 0MiB /  8191MiB  |           |                       |

+------------------+----------------------------------+-----------+-----------------------+

|  0   12   0   5  |              12MiB /  4864MiB    | 14      0 |  1   0    0    0    0 |

|                  |                 0MiB /  8191MiB  |           |                       |

+------------------+----------------------------------+-----------+-----------------------+

|  0   13   0   6  |              12MiB /  4864MiB    | 14      0 |  1   0    0    0    0 |

|                  |                 0MiB /  8191MiB  |           |                       |

+------------------+----------------------------------+-----------+-----------------------+

|  1    7   0   0  |              12MiB /  4864MiB    | 14      0 |  1   0    0    0    0 |

|                  |                 0MiB /  8191MiB  |           |                       |

+------------------+----------------------------------+-----------+-----------------------+

|  1    8   0   1  |              12MiB /  4864MiB    | 14      0 |  1   0    0    0    0 |

|                  |                 0MiB /  8191MiB  |           |                       |

+------------------+----------------------------------+-----------+-----------------------+

|  1    9   0   2  |              12MiB /  4864MiB    | 14      0 |  1   0    0    0    0 |

|                  |                 0MiB /  8191MiB  |           |                       |

+------------------+----------------------------------+-----------+-----------------------+

|  1   11   0   3  |              12MiB /  4864MiB    | 14      0 |  1   0    0    0    0 |

|                  |                 0MiB /  8191MiB  |           |                       |

+------------------+----------------------------------+-----------+-----------------------+

|  1   12   0   4  |              12MiB /  4864MiB    | 14      0 |  1   0    0    0    0 |

|                  |                 0MiB /  8191MiB  |           |                       |

+------------------+----------------------------------+-----------+-----------------------+

|  1   13   0   5  |              12MiB /  4864MiB    | 14      0 |  1   0    0    0    0 |

|                  |                 0MiB /  8191MiB  |           |                       |

+------------------+----------------------------------+-----------+-----------------------+

|  1   14   0   6  |              12MiB /  4864MiB    | 14      0 |  1   0    0    0    0 |

|                  |                 0MiB /  8191MiB  |           |                       |

+------------------+----------------------------------+-----------+-----------------------+

+-----------------------------------------------------------------------------------------+

| Processes:                                                                              |

|  GPU   GI   CI        PID   Type   Process name                              GPU Memory |

|        ID   ID                                                               Usage      |

|=========================================================================================|

|  No running processes found                                                             |

+-----------------------------------------------------------------------------------------+

^[[A[root@nvidia-driver-daemonset-414 drivers]# nvidia-smi -L

GPU 0: NVIDIA A100-PCIE-40GB (UUID: GPU-82127a6f-5b13-dae6-9e99-93b9c551a766)

  MIG 1g.5gb      Device  0: (UUID: MIG-9223c9a5-a2b6-504f-9465-4c9764777be8)

  MIG 1g.5gb      Device  1: (UUID: MIG-4030df33-00e8-5c7e-a2cb-375ca86ebd4b)

  MIG 1g.5gb      Device  2: (UUID: MIG-dc5d1253-de46-55c3-a358-9689047be048)

  MIG 1g.5gb      Device  3: (UUID: MIG-ab8ac52a-c665-56ba-a83e-87c66eae86b4)

  MIG 1g.5gb      Device  4: (UUID: MIG-efa728c7-8f33-5e8a-8e6f-23c05f964d5f)

  MIG 1g.5gb      Device  5: (UUID: MIG-3fd52b54-0a77-50d2-a2a9-b3c565ddcc44)

  MIG 1g.5gb      Device  6: (UUID: MIG-ffce2e58-cd76-5abe-9bb0-c4133161ad0d)

GPU 1: NVIDIA A100-PCIE-40GB (UUID: GPU-c4af0a46-3a24-8b5c-0a96-f5b0470a81e7)

  MIG 1g.5gb      Device  0: (UUID: MIG-60bc6e90-27d9-503c-96d3-fb00cc133241)

  MIG 1g.5gb      Device  1: (UUID: MIG-161cfcd7-bc64-530c-9e8a-e11d5cad19ed)

  MIG 1g.5gb      Device  2: (UUID: MIG-2ca754cd-a42b-5eb0-bda2-a89cbf219bf7)

  MIG 1g.5gb      Device  3: (UUID: MIG-184e1b7d-4473-58d2-a18a-8bd0ae0fabcd)

  MIG 1g.5gb      Device  4: (UUID: MIG-70563728-2f91-5a06-ae29-77c034d09e96)

  MIG 1g.5gb      Device  5: (UUID: MIG-cb7e193b-b7c7-5dc7-ad28-e38b63ac569f)

  MIG 1g.5gb      Device  6: (UUID: MIG-bd355cf4-c07b-5012-8b20-5be1aa49a0dc)
```

Steps to reproduce the issue:
oc label node nvidia.com/mig.config: all-enabled \
nvidia.com/mig-7g.40gb.count: '1' \
nvidia.com/mig-1g.5gb.count: '7' --overwrite

I'd appreciate any guidance I could get with this issue. 
Thanks!

**Comment by cdesiniotis** [comment]
@marlowsw you will want to create a custom MIG Manager configuration like below:

```
      custom-a100-40gb-config:
        - devices: [0]
          mig-enabled: true
          mig-devices:
            "1g.5gb": 7
        - devices: [1]
          mig-enabled: true
          mig-devices:
            "7g.40gb": 1
```

The above configuration tells MIG Manager to create 7x 1g.5gb instances on GPU at index 0 and 1x 7g.40gb instances on GPU at index 1.

Refer to our documentation on how to apply a custom MIG Manager configuration with GPU Operator: https://docs.nvidia.com/datacenter/cloud-native/gpu-operator/latest/gpu-operator-mig.html#example-custom-mig-configuration

You should not be modifying the `nvidia.com/mig-<profile>.count` labels yourself. The only label you will want to modify is `nvidia.com/mig.config` to apply the desired configuration, and the other labels will get updated accordingly once the MIG devices are created.
